// 園芸作物データ
// growTime: 分単位
// weedCount: 草抜き回数（全作物3回固定）
// prices: [☆1, ☆2, ☆3, ☆4, ☆5] null = 未確認
// auth: 認証マスター対象か
// isEvent: イベント限定か
// eventName: イベント名（isEvent=trueの場合）

const cropData = [

  // ── 通常作物 ────────────────────────
  {
    name: "トマト",
    img: "./images/crops/tomato.PNG",
    seedImg: "./images/crops/seed_tomato.jpg",
    level: 1,
    growTime: 15,
    seedPrice: 10,
    prices: [30, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 1,
  },
  {
    name: "ジャガイモ",
    img: "./images/crops/potato.PNG",
    seedImg: "./images/crops/seed_potato.jpg",
    level: 1,
    growTime: 60,
    seedPrice: 30,
    prices: [90, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 2,
  },
  {
    name: "稲",
    img: "./images/crops/ine.PNG",
    seedImg: "./images/crops/seed_ine.jpg",
    level: 1,
    growTime: 20,
    seedPrice: 12,
    prices: [37, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 3,
  },
  {
    name: "小麦",
    img: "./images/crops/wheat.PNG",
    seedImg: "./images/crops/seed_wheat.jpg",
    level: 2,
    growTime: 240,
    seedPrice: 95,
    prices: [285, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 4,
  },
  {
    name: "レタス",
    img: "./images/crops/lettuce.PNG",
    seedImg: "./images/crops/seed_lettuce.jpg",
    level: 3,
    growTime: 480,
    seedPrice: 145,
    prices: [435, 582, 726, 870, 1305],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 5,
  },
  {
    name: "パイナップル",
    img: "./images/crops/pineapple.PNG",
    seedImg: "./images/crops/seed_pineapple.jpg",
    level: 4,
    growTime: 30,
    seedPrice: 15,
    prices: [52, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 6,
  },
  {
    name: "ニンジン",
    img: "./images/crops/carrot.PNG",
    seedImg: "./images/crops/seed_carrot.jpg",
    level: 5,
    growTime: 120,
    seedPrice: 50,
    prices: [155, 207, 258, 310, 465],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 7,
  },
  {
    name: "いちご",
    img: "./images/crops/strawberry.PNG",
    seedImg: "./images/crops/seed_strawberry.jpg",
    level: 6,
    growTime: 360,
    seedPrice: 125,
    prices: [375, 502, 626, 750, 1125],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 8,
  },
  {
    name: "トウモロコシ",
    img: "./images/crops/corn.PNG",
    seedImg: "./images/crops/seed_corn.jpg",
    level: 6,
    growTime: 720,
    seedPrice: 170,
    prices: [515, 690, 860, 1030, 1545],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 9,
  },
  {
    name: "ブドウ",
    img: "./images/crops/grape.PNG",
    seedImg: "./images/crops/seed_grape.jpg",
    level: 7,
    growTime: 600,
    seedPrice: 160,
    prices: [480, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 10,
  },
  {
    name: "ナス",
    img: "./images/crops/eggplant.PNG",
    seedImg: "./images/crops/seed_eggplant.jpg",
    level: 8,
    growTime: 420,
    seedPrice: 135,
    prices: [406, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 11,
  },
  {
    name: "茶葉",
    img: "./images/crops/tea.PNG",
    seedImg: "./images/crops/seed_tea.jpg",
    level: 11,
    growTime: 45,
    seedPrice: 25,
    prices: [75, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 12,
  },
  {
    name: "カカオ豆",
    img: "./images/crops/cacao.PNG",
    seedImg: "./images/crops/seed_cacao.jpg",
    level: 12,
    growTime: 300,
    seedPrice: 110,
    prices: [330, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 13,
  },
  {
    name: "アボカド",
    img: "./images/crops/avocado.PNG",
    seedImg: "./images/crops/seed_avocado.jpg",
    level: 13,
    growTime: 840,
    seedPrice: 180,
    prices: [549, null, null, null, null],
    weedCount: 3,
    auth: true,
    isEvent: false,
    eventName: null,
    bookIndex: 14,
  },

  // ── イベント作物 ────────────────────────
  {
    name: "ダイコン",
    img: "./images/crops/daikon.PNG",
    seedImg: "./images/crops/seed_daikon.jpg",
    level: 1,
    growTime: 15,
    seedPrice: 10,
    prices: [30, null, null, null, null],
    weedCount: 3,
    auth: false,
    isEvent: true,
    eventName: "スノーシーズン",
    bookIndex: 15,
  },
  {
    name: "ロメインレタス",
    img: "./images/crops/romaine.PNG",
    seedImg: "./images/crops/seed_romaine.jpg",
    level: 1,
    growTime: 15,
    seedPrice: 10,
    prices: [30, null, null, null, null],
    weedCount: 3,
    auth: false,
    isEvent: true,
    eventName: "ドリームライト",
    bookIndex: 16,
  },
  {
    name: "レモンバーベナ",
    img: "./images/crops/lemon_verbena.PNG",
    seedImg: "./images/crops/seed_lemon_verbena.jpg",
    level: 1,
    growTime: 15,
    seedPrice: 10,
    prices: [30, null, null, null, null],
    weedCount: 3,
    auth: false,
    isEvent: true,
    eventName: "ブロック市街地",
    bookIndex: 17,
  },
];
