// ギフトコードデータ
// active: true = 有効, false = 配布終了（期限前でも無効にしたい場合）
// expiry: "YYYY-MM-DD" 形式。期限なしの場合は null

const codesData = [
  {
    code: "heartopia0108",
    reward: "月の水晶×100",
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: null,
    active: false,
  },
  {
    code: "dcthx4u",
    reward: "願い星×10",
    rewardI18n:{"ja":"願い星×10","en":"Wish Star ×10","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×10","en":"Wish Star ×10","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-06-30 12:00",
    active: true,
  },
  {
    code: "letsparty",
    reward: "願い星×15，コイン×5000，修理箱×3",
    rewardI18n:{"ja":"願い星×15，コイン×5000，修理箱×3","en":"Wish Star ×15, Coin ×5000, Repair Kit ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: null,
    active: false,
  },
  {
    code: "true5mthks",
    reward: "シェフ特製サラダ×2，良質木材×10，低木の枝×20",
    rewardI18n:{"ja":"シェフ特製サラダ×2，良質木材×10，低木の枝×20","en":"Chef's Special Salad ×2, Quality Wood ×10, Shrub Branch ×20","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: null,
    active: false,
  },
  {
    code: "letsdressup",
    reward: "願い星×15，コイン×5000，栄養剤×10",
    rewardI18n:{"ja":"願い星×15，コイン×5000，栄養剤×10","en":"Wish Star ×15, Coin ×5000, Nutrient Supplement ×10","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: null,
    active: false,
  },
  {
    code: "HAPPY2026",
    reward: "月の水晶×10，コイン×8888",
    rewardI18n:{"ja":"月の水晶×10，コイン×8888","en":"Moon Crystal ×10, Coin ×8888","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: null,
    active: false,
  },
  {
    code: "lifewithline",
    reward: "願い星×10",
    rewardI18n:{"ja":"願い星×10","en":"Wish Star ×10","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×10","en":"Wish Star ×10","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: null,
    active: true,
  },
  {
    code: "Junegift",
    reward: "月の水晶×50，可愛いパンダのシャボン玉液×5，黒顔パンダのシャボン玉液×5",
    rewardI18n:{"ja":"月の水晶×50，可愛いパンダのシャボン玉液×5，黒顔パンダのシャボン玉液×5","en":"Moon Crystal ×50, Cute Panda Bubble Solution ×5, Black-faced Panda Bubble Solution ×5","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-07-01 00:59",
    active: true,
  },
  {
    code: "shakeurbody",
    reward: "限定エモート",
    rewardI18n:{"ja":"限定エモート","en":"Limited Emote","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-07-01 00:59",
    active: true,
  },
  {
    code: "n3k7q5a8m2",
    reward: "願い星×3，ツルツルオーク×1，コーヒー豆×3",
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "p9m4r1a6k7",
    reward: "願い星×3，ツルツルオーク×1，コーヒー豆×3",
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "a5r8k2m7q4",
    reward: "願い星×3，ツルツルオーク×1，コーヒー豆×3",
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルオーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "happyjune2026",
    reward: "願い星×15，稲の種×3，肉×10，あずき×10",
    rewardI18n:{"ja":"願い星×15，稲の種×3，肉×10，あずき×10","en":"Wish Star ×15, Rice Seeds ×3, Meat ×10, Red Beans ×10","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-07-01 00:59",
    active: true,
  },
  {
    code: "dadstrong4ever",
    reward: "願い星×5，肥料×10，りんご×10",
    rewardI18n:{"ja":"願い星×5，肥料×10，りんご×10","en":"Wish Star ×5, Fertilizer ×10, Apple ×10","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-07-01 00:59",
    active: true,
  },
  {
    code: "k1n6q9m3p8",
    reward: "願い星×3，ツルツルウォーク×1，コーヒー豆×1",
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "180daysjoy",
    reward: "月の水晶×100",
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "callofwhales0709",
    reward: "月の水晶×100",
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "oceanguardians",
    reward: "月の水晶×100",
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"月の水晶×100","en":"Moon Crystal ×100","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "q7a3p5r2k6",
    reward: "願い星×3，ツルツルウォーク×1，コーヒー豆×1",
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "m8p2a7n4r9",
    reward: "願い星×3，ツルツルウォーク×1，コーヒー豆×1",
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×1","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×1","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "Cherish180",
    reward: "月の水晶×40,願い星×20,そのほか豪華アイテム！",
    rewardI18n:{"ja":"月の水晶×40,願い星×20,そのほか豪華アイテム！","en":"Moon Crystal ×40, Wish Star ×20, and other deluxe items!","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "halfyear180",
    reward: "月の水晶×30,願い星×10,そのほか豪華アイテム！",
    rewardI18n:{"ja":"月の水晶×30,願い星×10,そのほか豪華アイテム！","en":"Moon Crystal ×30, Wish Star ×10, and other deluxe items!","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "together180",
    reward: "月の水晶×40,願い星×20,そのほか豪華アイテム！",
    rewardI18n:{"ja":"月の水晶×40,願い星×20,そのほか豪華アイテム！","en":"Moon Crystal ×40, Wish Star ×20, and other deluxe items!","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  {
    code: "r4k9q1a5m6",
    reward: "願い星×3，ツルツルウォーク×1，コーヒー豆×3",
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    rewardI18n:{"ja":"願い星×3，ツルツルウォーク×1，コーヒー豆×3","en":"Wish Star ×3, Smooth Oak ×1, Coffee Beans ×3","zh-CN":"","zh-TW":"","ko":"","th":""},
    expiry: "2026-08-01 00:59",
    active: true,
  },
  // 以下、コードを追加していく
  // {
  //   code: "SPRING2026",
  //   reward: "花の種×10、ゴールド×500",
  //   expiry: "2026-06-30",
  //   active: true,
  // },
];
