const catFoods = [
{id:"001",name:{jp:"動物汎用エサ",en:"Generic Feed",zh_cn:"通用饲料",zh_tw:"通用飼料",ko:"범용 사료",th:"อาหารทั่วไป",tl:"Pangkalahatang pagkain"},img:"./images/petfoods/001.PNG"},
{id:"033",name:{jp:"キャットフード",en:"Cat Food",zh_cn:"猫粮",zh_tw:"貓糧",ko:"고양이 사료",th:"อาหารแมว",tl:"Cat food"},img:"./images/petfoods/033.PNG"},
{id:"034",name:{jp:"ヨーロピアンパーチ",en:"European Perch",zh_cn:"欧洲鲈鱼",zh_tw:"歐洲鱸魚",ko:"유럽 농어",th:"ปลาคอนยุโรป",tl:"European perch"},img:"./images/petfoods/034.PNG"},
{id:"036",name:{jp:"チャブ",en:"Chub",zh_cn:"鲢鱼",zh_tw:"白魚",ko:"처브",th:"ปลาชับ",tl:"Chub"},img:"./images/petfoods/036.PNG"},
{id:"037",name:{jp:"シマドジョウ",en:"Loach",zh_cn:"泥鳅",zh_tw:"泥鰍",ko:"미꾸라지",th:"ปลาช่อนนา",tl:"Loach"},img:"./images/petfoods/037.PNG"},
{id:"038",name:{jp:"バーベル",en:"Barbel",zh_cn:"须鲤",zh_tw:"鬚鯉",ko:"바벨",th:"ปลาบาร์เบล",tl:"Barbel"},img:"./images/petfoods/038.PNG"},
{id:"039",name:{jp:"ダヌープストレバー",en:"Danube Sturgeon",zh_cn:"多瑙河鲟",zh_tw:"多瑙河鱘",ko:"다뉴브 철갑상어",th:"ปลาสเตอร์เจียน",tl:"Sturgeon"},img:"./images/petfoods/039.PNG"},
{id:"040",name:{jp:"ミノー",en:"Minnow",zh_cn:"小鱼",zh_tw:"小魚",ko:"미노우",th:"ปลาตัวเล็ก",tl:"Minnow"},img:"./images/petfoods/040.PNG"},
{id:"041",name:{jp:"ティラピア",en:"Tilapia",zh_cn:"罗非鱼",zh_tw:"羅非魚",ko:"틸라피아",th:"ปลานิล",tl:"Tilapia"},img:"./images/petfoods/041.PNG"},
{id:"042",name:{jp:"テンチ",en:"Tench",zh_cn:"丁鱥",zh_tw:"丁鱥",ko:"텐치",th:"ปลาเทนช์",tl:"Tench"},img:"./images/petfoods/042.PNG"},
{id:"043",name:{jp:"ホワイトフィッシュ",en:"Whitefish",zh_cn:"白鱼",zh_tw:"白魚",ko:"화이트피쉬",th:"ปลาขาว",tl:"Whitefish"},img:"./images/petfoods/043.PNG"},
{id:"044",name:{jp:"マブナ",en:"Crucian Carp",zh_cn:"鲫鱼",zh_tw:"鯽魚",ko:"붕어",th:"ปลาคาร์พ",tl:"Carp"},img:"./images/petfoods/044.PNG"},
{id:"045",name:{jp:"ブリーク",en:"Bleak",zh_cn:"白条鱼",zh_tw:"白條魚",ko:"블릭",th:"ปลาเบลค",tl:"Bleak"},img:"./images/petfoods/045.PNG"},
{id:"046",name:{jp:"シュナイダー",en:"Schneider Fish",zh_cn:"施耐德鱼",zh_tw:"施耐德魚",ko:"슈나이더",th:"ปลาシュナイダー",tl:"Schneider"},img:"./images/petfoods/046.PNG"},
{id:"047",name:{jp:"コウライエビ",en:"Kuruma Shrimp",zh_cn:"斑节虾",zh_tw:"斑節蝦",ko:"중하",th:"กุ้งกุลาดำ",tl:"Shrimp"},img:"./images/petfoods/047.PNG"},
{id:"048",name:{jp:"ニシイワシ",en:"Sardine",zh_cn:"沙丁鱼",zh_tw:"沙丁魚",ko:"정어리",th:"ปลาซาร์ดีน",tl:"Sardine"},img:"./images/petfoods/048.PNG"},
{id:"049",name:{jp:"スズキ",en:"Sea Bass",zh_cn:"海鲈鱼",zh_tw:"海鱸魚",ko:"농어",th:"ปลากะพง",tl:"Sea Bass"},img:"./images/petfoods/049.PNG"},
{id:"050",name:{jp:"カツオ",en:"Bonito",zh_cn:"鲣鱼",zh_tw:"鰹魚",ko:"가다랑어",th:"ปลาโอ",tl:"Bonito"},img:"./images/petfoods/050.PNG"},
{id:"051",name:{jp:"タチウオ",en:"Cutlassfish",zh_cn:"带鱼",zh_tw:"帶魚",ko:"갈치",th:"ปลาดาบ",tl:"Cutlassfish"},img:"./images/petfoods/051.PNG"},
{id:"052",name:{jp:"ウミエビ",en:"Sea Shrimp",zh_cn:"海虾",zh_tw:"海蝦",ko:"바다새우",th:"กุ้งทะเล",tl:"Shrimp"},img:"./images/petfoods/052.PNG"},
{id:"053",name:{jp:"マアジ",en:"Horse Mackerel",zh_cn:"竹荚鱼",zh_tw:"竹筴魚",ko:"전갱이",th:"ปลาทู",tl:"Mackerel"},img:"./images/petfoods/053.PNG"},
{id:"054",name:{jp:"カイブツギンザメ",en:"Chimaera",zh_cn:"银鲛",zh_tw:"銀鮫",ko:"키메라",th:"ปลาฉลามผี",tl:"Chimaera"},img:"./images/petfoods/054.PNG"},
{id:"055",name:{jp:"ウミトゲウオ",en:"Stickleback",zh_cn:"刺鱼",zh_tw:"刺魚",ko:"가시고기",th:"ปลาหนาม",tl:"Stickleback"},img:"./images/petfoods/055.PNG"},
{id:"056",name:{jp:"ストライプトレッドマレット",en:"Striped Mullet",zh_cn:"条纹鲻鱼",zh_tw:"條紋鯔魚",ko:"줄무늬 숭어",th:"ปลากระบอกลาย",tl:"Mullet"},img:"./images/petfoods/056.PNG"},
{id:"057",name:{jp:"イシドジョウ",en:"Stone Loach",zh_cn:"石泥鳅",zh_tw:"石泥鰍",ko:"돌미꾸라지",th:"ปลาช่อนหิน",tl:"Loach"},img:"./images/petfoods/057.PNG"},
{id:"058",name:{jp:"マッドサンフィッシュ",en:"Mud Sunfish",zh_cn:"泥太阳鱼",zh_tw:"泥太陽魚",ko:"머드 선피시",th:"ปลาซันฟิชโคลน",tl:"Sunfish"},img:"./images/petfoods/058.PNG"},
{id:"059",name:{jp:"キュウリウオ",en:"Smelt",zh_cn:"胡瓜鱼",zh_tw:"胡瓜魚",ko:"빙어",th:"ปลากลิ่นแตง",tl:"Smelt"},img:"./images/petfoods/059.PNG"},
{id:"060",name:{jp:"ラッフ",en:"Ruffe",zh_cn:"欧鳜",zh_tw:"歐鱸",ko:"러프",th:"ปลารัฟฟ์",tl:"Ruffe"},img:"./images/petfoods/060.PNG"},
{id:"061",name:{jp:"フランスアジ",en:"French Jack",zh_cn:"法国鲹鱼",zh_tw:"法國鯵魚",ko:"프랑스 전갱이",th:"ปลาทูฝรั่งเศส",tl:"Jack fish"},img:"./images/petfoods/061.PNG"},
{id:"063",name:{jp:"アンコウ",en:"Anglerfish",zh_cn:"鮟鱇鱼",zh_tw:"鮟鱇魚",ko:"아귀",th:"ปลาอังเกลอร์",tl:"Anglerfish"},img:"./images/petfoods/063.PNG"},
{id:"064",name:{jp:"イガイ",en:"Mussel",zh_cn:"贻贝",zh_tw:"貽貝",ko:"홍합",th:"หอยแมลงภู่",tl:"Mussel"},img:"./images/petfoods/064.PNG"},
{id:"065",name:{jp:"パイクパーチ",en:"Pike Perch",zh_cn:"梭鲈",zh_tw:"梭鱸",ko:"파이크 퍼치",th:"ปลาพาइक",tl:"Perch"},img:"./images/petfoods/065.PNG"},
{id:"066",name:{jp:"オタマジャクシ",en:"Tadpole",zh_cn:"蝌蚪",zh_tw:"蝌蚪",ko:"올챙이",th:"ลูกอ๊อด",tl:"Tadpole"},img:"./images/petfoods/066.PNG"},
{id:"067",name:{jp:"北欧アカザエビ",en:"Nordic Lobster",zh_cn:"北欧红龙虾",zh_tw:"北歐紅龍蝦",ko:"노르딕 랍스터",th:"กุ้งล็อบสเตอร์ยุโรป",tl:"Lobster"},img:"./images/petfoods/067.PNG"},
{id:"068",name:{jp:"マダコ",en:"Octopus",zh_cn:"章鱼",zh_tw:"章魚",ko:"문어",th:"ปลาหมึกยักษ์",tl:"Octopus"},img:"./images/petfoods/068.PNG"},
{id:"069",name:{jp:"タイセイヨウサケ",en:"Atlantic Salmon",zh_cn:"大西洋鲑鱼",zh_tw:"大西洋鮭魚",ko:"대서양 연어",th:"ปลาแซลมอนแอตแลนติก",tl:"Salmon"},img:"./images/petfoods/069.PNG"},
{id:"070",name:{jp:"ピグミータコ",en:"Pygmy Octopus",zh_cn:"小型章鱼",zh_tw:"小型章魚",ko:"피그미 문어",th:"หมึกตัวเล็ก",tl:"Octopus"},img:"./images/petfoods/070.PNG"},
{id:"071",name:{jp:"ヤドカリ",en:"Hermit Crab",zh_cn:"寄居蟹",zh_tw:"寄居蟹",ko:"소라게",th:"ปูเสฉวน",tl:"Hermit crab"},img:"./images/petfoods/071.PNG"},
{id:"072",name:{jp:"カクレクマノミ",en:"Clownfish",zh_cn:"小丑鱼",zh_tw:"小丑魚",ko:"흰동가리",th:"ปลาการ์ตูน",tl:"Clownfish"},img:"./images/petfoods/072.PNG"},
{id:"073",name:{jp:"オオクチバス",en:"Largemouth Bass",zh_cn:"大口黑鲈",zh_tw:"大口黑鱸",ko:"큰입배스",th:"ปลากะพงปากใหญ่",tl:"Bass"},img:"./images/petfoods/073.PNG"},
{id:"074",name:{jp:"ヨーロッパコイ",en:"Common Carp",zh_cn:"鲤鱼",zh_tw:"鯉魚",ko:"잉어",th:"ปลาคาร์พ",tl:"Carp"},img:"./images/petfoods/074.PNG"},
{id:"075",name:{jp:"カワメンタイ",en:"Burbot",zh_cn:"江鳕",zh_tw:"江鱈",ko:"버봇",th:"ปลาบูร์บอต",tl:"Burbot"},img:"./images/petfoods/075.PNG"},
{id:"076",name:{jp:"ハゼ",en:"Goby",zh_cn:"虾虎鱼",zh_tw:"蝦虎魚",ko:"망둑어",th:"ปลาบู่",tl:"Goby"},img:"./images/petfoods/076.PNG"},
{id:"077",name:{jp:"サワガニ",en:"Freshwater Crab",zh_cn:"淡水蟹",zh_tw:"淡水蟹",ko:"민물게",th:"ปูน้ำจืด",tl:"Crab"},img:"./images/petfoods/077.PNG"},
{id:"078",name:{jp:"イシビラメ",en:"Turbot",zh_cn:"比目鱼",zh_tw:"比目魚",ko:"가자미",th:"ปลาลิ้นหมา",tl:"Flatfish"},img:"./images/petfoods/078.PNG"},
{id:"079",name:{jp:"ヨーロッパヒラメ",en:"European Flounder",zh_cn:"欧洲比目鱼",zh_tw:"歐洲比目魚",ko:"유럽 가자미",th:"ปลาลิ้นหมายุโรป",tl:"Flounder"},img:"./images/petfoods/079.PNG"},
{id:"080",name:{jp:"レッドベリーピラニア",en:"Red-bellied Piranha",zh_cn:"红腹食人鱼",zh_tw:"紅腹食人魚",ko:"피라냐",th:"ปลาปิรันย่า",tl:"Piranha"},img:"./images/petfoods/080.PNG"},
{id:"081",name:{jp:"バタフライコイ",en:"Butterfly Koi",zh_cn:"锦鲤",zh_tw:"錦鯉",ko:"나비 잉어",th:"ปลาคาร์พแฟนซี",tl:"Koi"},img:"./images/petfoods/081.PNG"},
{id:"082",name:{jp:"カワギンポ",en:"Blenny",zh_cn:"鳚鱼",zh_tw:"鳚魚",ko:"블레니",th:"ปลาบลินนี",tl:"Blenny"},img:"./images/petfoods/082.PNG"},
{id:"083",name:{jp:"マス",en:"Trout",zh_cn:"鳟鱼",zh_tw:"鱒魚",ko:"송어",th:"ปลาเทราต์",tl:"Trout"},img:"./images/petfoods/083.PNG"},
{id:"084",name:{jp:"ラッド",en:"Rudd",zh_cn:"红鳍鲮",zh_tw:"紅鰭鱮",ko:"러드",th:"ปลารัดด์",tl:"Rudd"},img:"./images/petfoods/084.PNG"},
{id:"085",name:{jp:"タイセイヨウサバ",en:"Atlantic Mackerel",zh_cn:"大西洋鲭鱼",zh_tw:"大西洋鯖魚",ko:"대서양 고등어",th:"ปลาซาบะแอตแลนติก",tl:"Mackerel"},img:"./images/petfoods/085.PNG"},
{id:"086",name:{jp:"ヨーロッパロブスター",en:"European Lobster",zh_cn:"欧洲龙虾",zh_tw:"歐洲龍蝦",ko:"유럽 랍스터",th:"ล็อบสเตอร์ยุโรป",tl:"Lobster"},img:"./images/petfoods/086.PNG"},
{id:"087",name:{jp:"ヨーロッパスルメイカ",en:"European Squid",zh_cn:"欧洲鱿鱼",zh_tw:"歐洲魷魚",ko:"유럽 오징어",th:"ปลาหมึกยุโรป",tl:"Squid"},img:"./images/petfoods/087.PNG"},
{id:"089",name:{jp:"フグ",en:"Pufferfish",zh_cn:"河豚",zh_tw:"河豚",ko:"복어",th:"ปลาปักเป้า",tl:"Pufferfish"},img:"./images/petfoods/089.PNG"},
{id:"090",name:{jp:"シロザケ",en:"Chum Salmon",zh_cn:"狗鲑",zh_tw:"狗鮭",ko:"백연어",th:"ปลาแซลมอนชัม",tl:"Salmon"},img:"./images/petfoods/090.PNG"},
{id:"091",name:{jp:"カワヒメマス",en:"Arctic Char",zh_cn:"北极红点鲑",zh_tw:"北極紅點鮭",ko:"북극이빨고기",th:"ปลาอาร์กติกชาร์",tl:"Char"},img:"./images/petfoods/091.PNG"},
{id:"092",name:{jp:"タフ・ガーナード",en:"Gurnard",zh_cn:"红鲉",zh_tw:"紅鮋",ko:"거너드",th:"ปลากันนาร์ด",tl:"Gurnard"},img:"./images/petfoods/092.PNG"},
{id:"093",name:{jp:"イトヨ",en:"Three-spined Stickleback",zh_cn:"三刺鱼",zh_tw:"三刺魚",ko:"가시고기",th:"ปลาหนามสามแฉก",tl:"Stickleback"},img:"./images/petfoods/093.PNG"},
{id:"094",name:{jp:"アプロケイルス",en:"Aplocheilus",zh_cn:"青鳉鱼",zh_tw:"青鱂魚",ko:"아프로케일루스",th:"ปลาน้ำจืดเล็ก",tl:"Killifish"},img:"./images/petfoods/094.PNG"},
{id:"095",name:{jp:"カジカ",en:"Sculpin",zh_cn:"杜父鱼",zh_tw:"杜父魚",ko:"카지카",th:"ปลากระเบนเล็ก",tl:"Sculpin"},img:"./images/petfoods/095.PNG"},
{id:"096",name:{jp:"リュウグウノツカイ",en:"Oarfish",zh_cn:"皇带鱼",zh_tw:"皇帶魚",ko:"산갈치",th:"ปลาออร์ฟิช",tl:"Oarfish"},img:"./images/petfoods/096.PNG"},
{id:"097",name:{jp:"スペインダイ",en:"Red Seabream",zh_cn:"红鲷鱼",zh_tw:"紅鯛魚",ko:"참돔",th:"ปลากะพงแดง",tl:"Sea bream"},img:"./images/petfoods/097.PNG"},
{id:"098",name:{jp:"ヨーロッパウナギ",en:"European Eel",zh_cn:"欧洲鳗鱼",zh_tw:"歐洲鰻魚",ko:"유럽 장어",th:"ปลาไหลยุโรป",tl:"Eel"},img:"./images/petfoods/098.PNG"},
{id:"099",name:{jp:"黄金タラバガニ",en:"Golden King Crab",zh_cn:"黄金帝王蟹",zh_tw:"黃金帝王蟹",ko:"황금 대게",th:"ปูยักษ์ทอง",tl:"King crab"},img:"./images/petfoods/099.PNG"},
{id:"100",name:{jp:"マッドミノー",en:"Mud Minnow",zh_cn:"泥鳉鱼",zh_tw:"泥鰷魚",ko:"머드 미노우",th:"ปลาตัวเล็กโคลน",tl:"Minnow"},img:"./images/petfoods/100.PNG"},
{id:"101",name:{jp:"北欧ブルーアカザエビ",en:"Nordic Blue Shrimp",zh_cn:"北欧蓝虾",zh_tw:"北歐藍蝦",ko:"북유럽 블루 새우",th:"กุ้งสีน้ำเงินนอร์ดิก",tl:"Nordic Blue Shrimp"},img:"./images/petfoods/101.PNG"},
{id:"102",name:{jp:"キンギョ",en:"Goldfish",zh_cn:"金鱼",zh_tw:"金魚",ko:"금붕어",th:"ปลาทอง",tl:"Goldfish"},img:"./images/petfoods/102.PNG"},
{id:"103",name:{jp:"タラバガニ",en:"King Crab",zh_cn:"帝王蟹",zh_tw:"帝王蟹",ko:"킹크랩",th:"ปูคิงแครบ",tl:"King Crab"},img:"./images/petfoods/103.PNG"},
{id:"104",name:{jp:"モンツキダラ",en:"Haddock",zh_cn:"黑线鳕",zh_tw:"黑線鱈",ko:"대구류",th:"ปลาฮัดด็อก",tl:"Haddock"},img:"./images/petfoods/104.PNG"},
{id:"105",name:{jp:"ノーザンパイク",en:"Northern Pike",zh_cn:"北梭鱼",zh_tw:"北梭魚",ko:"노던 파이크",th:"ปลาหอกเหนือ",tl:"Northern Pike"},img:"./images/petfoods/105.PNG"},
{id:"106",name:{jp:"パンプキンシード",en:"Pumpkinseed Sunfish",zh_cn:"南瓜籽鱼",zh_tw:"南瓜籽魚",ko:"펌킨시드",th:"ปลาพัมพ์คินซีด",tl:"Pumpkinseed"},img:"./images/petfoods/106.PNG"},
{id:"107",name:{jp:"ドナウイトウ",en:"Danube Salmon",zh_cn:"多瑙鲑",zh_tw:"多瑙鮭",ko:"다뉴브 연어",th:"ปลาแซลมอนดานูบ",tl:"Danube Salmon"},img:"./images/petfoods/107.PNG"},
{id:"108",name:{jp:"ミナミマグロ",en:"Southern Bluefin Tuna",zh_cn:"南方蓝鳍金枪鱼",zh_tw:"南方黑鮪魚",ko:"남방참다랑어",th:"ปลาทูน่าครีบน้ำเงินใต้",tl:"Southern Bluefin Tuna"},img:"./images/petfoods/108.PNG"},
{id:"109",name:{jp:"マンボウ",en:"Ocean Sunfish",zh_cn:"翻车鱼",zh_tw:"翻車魚",ko:"개복치",th:"ปลาแสงอาทิตย์",tl:"Sunfish"},img:"./images/petfoods/109.PNG"},
{id:"110",name:{jp:"アカマンボウ",en:"Opah",zh_cn:"月鱼",zh_tw:"月魚",ko:"오파",th:"ปลาโอปาห์",tl:"Opah"},img:"./images/petfoods/110.PNG"},
{id:"111",name:{jp:"ヨーロッパナマズ",en:"Wels Catfish",zh_cn:"欧洲鲶鱼",zh_tw:"歐洲鯰魚",ko:"유럽 메기",th:"ปลาดุกยุโรป",tl:"Wels Catfish"},img:"./images/petfoods/111.PNG"},
{id:"112",name:{jp:"ブルーギル",en:"Bluegill",zh_cn:"蓝鳃太阳鱼",zh_tw:"藍鰓太陽魚",ko:"블루길",th:"ปลาบลูกิล",tl:"Bluegill"},img:"./images/petfoods/112.PNG"},
{id:"113",name:{jp:"ホッキョクイワナ",en:"Arctic Char Trout",zh_cn:"北极红点鲑",zh_tw:"北極紅點鮭",ko:"북극송어",th:"ปลาอาร์กติกเทราต์",tl:"Arctic Char"},img:"./images/petfoods/113.PNG"},
{id:"114",name:{jp:"メカジキ",en:"Swordfish",zh_cn:"剑鱼",zh_tw:"劍魚",ko:"황새치",th:"ปลากระโทงดาบ",tl:"Swordfish"},img:"./images/petfoods/114.PNG"},
{id:"000",name:{jp:"シマスズメダイ"},img:"./images/000.PNG"},
{id:"115",name:{jp:"氷晶のタラバガニ",en:"Ice Crystal King Crab",zh_cn:"冰晶帝王蟹",zh_tw:"冰晶帝王蟹",ko:"빙결 킹크랩",th:"ปูคิงคริสตัลน้ำแข็ง",tl:"Ice King Crab"},img:"./images/petfoods/115.PNG"},
{id:"116",name:{jp:"氷晶のマンボウ",en:"Ice Sunfish",zh_cn:"冰晶翻车鱼",zh_tw:"冰晶翻車魚",ko:"빙결 개복치",th:"ปลาแสงอาทิตย์น้ำแข็ง",tl:"Ice Sunfish"},img:"./images/petfoods/116.PNG"},
{id:"117",name:{jp:"氷晶のフグ",en:"Ice Pufferfish",zh_cn:"冰晶河豚",zh_tw:"冰晶河豚",ko:"빙결 복어",th:"ปลาปักเป้าน้ำแข็ง",tl:"Ice Pufferfish"},img:"./images/petfoods/117.PNG"},
{id:"118",name:{jp:"氷晶のタツノオトシゴ",en:"Ice Seahorse",zh_cn:"冰晶海马",zh_tw:"冰晶海馬",ko:"빙결 해마",th:"ม้าน้ำคริสตัลน้ำแข็ง",tl:"Ice Seahorse"},img:"./images/petfoods/118.PNG"},
{id:"119",name:{jp:"氷晶のジンベエザメ",en:"Ice Whale Shark",zh_cn:"冰晶鲸鲨",zh_tw:"冰晶鯨鯊",ko:"빙결 고래상어",th:"ฉลามวาฬน้ำแข็ง",tl:"Ice Whale Shark"},img:"./images/petfoods/119.PNG"},
{id:"120",name:{jp:"紺色帽のディレクタコ",en:"Director Octopus (Navy)",zh_cn:"导演章鱼（海军帽）",zh_tw:"導演章魚（海軍帽）",ko:"감독 문어(네이비)",th:"หมึกผู้กำกับ (หมวกน้ำเงิน)",tl:"Director Octopus"},img:"./images/petfoods/120.PNG"},
{id:"121",name:{jp:"茶色帽のディレクタコ",en:"Director Octopus (Brown)",zh_cn:"导演章鱼（棕帽）",zh_tw:"導演章魚（棕帽）",ko:"감독 문어(갈색)",th:"หมึกผู้กำกับ (หมวกน้ำตาล)",tl:"Director Octopus"},img:"./images/petfoods/121.PNG"},
{id:"122",name:{jp:"青色帽のディレクタコ",en:"Director Octopus (Blue)",zh_cn:"导演章鱼（蓝帽）",zh_tw:"導演章魚（藍帽）",ko:"감독 문어(파랑)",th:"หมึกผู้กำกับ (หมวกฟ้า)",tl:"Director Octopus"},img:"./images/petfoods/122.PNG"},
{id:"123",name:{jp:"褐色帽のディレクタマダコ",en:"Director Octopus (Brown V.)",zh_cn:"导演章鱼（褐色）",zh_tw:"導演章魚（褐色）",ko:"감독 문어(갈색 변형)",th:"หมึกผู้กำกับ (สีน้ำตาล)",tl:"Director Octopus"},img:"./images/petfoods/123.PNG"},
{id:"124",name:{jp:"柄帽のディレクタマダコ",en:"Director Octopus (Pattern)",zh_cn:"导演章鱼（花纹帽）",zh_tw:"導演章魚（花紋帽）",ko:"감독 문어(무늬)",th:"หมึกผู้กำกับ (ลาย)",tl:"Director Octopus"},img:"./images/petfoods/124.PNG"}
];
