// 魚
const fishData = [
{
 name:"ヨーロピアンパーチ",
 nameI18n:{"ja":"ヨーロピアンパーチ","en":"European Perch","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"中",
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"川",
 locationI18n:{"ja":"川","en":"River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/001.PNG"
},
{
 name:"ヨーロッパトノサマガエル",
 nameI18n:{"ja":"ヨーロッパトノサマガエル","en":"Edible Frog","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"青",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"湖",
 locationI18n:{"ja":"湖","en":"Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/002.PNG"
},
{
 name:"チャブ",
 nameI18n:{"ja":"チャブ","en":"Chub","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"中",
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"湖",
 locationI18n:{"ja":"湖","en":"Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/003.PNG"
},
{
 name:"シマドジョウ",
 nameI18n:{"ja":"シマドジョウ","en":"Striped Loach","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巨木の川",
 locationI18n:{"ja":"巨木の川","en":"Giant Tree River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/004.PNG"
},
{
 name:"バーベル",
 nameI18n:{"ja":"バーベル","en":"Barbel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"中",
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"浅水川",
 locationI18n:{"ja":"浅水川","en":"Shallow River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/005.PNG"
},
{
 name:"ダヌープストレバー",
 nameI18n:{"ja":"ダヌープストレバー","en":"Danube Streber","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"中",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"霞川",
 locationI18n:{"ja":"霞川","en":"Mist River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/006.PNG"
},
{
 name:"ミノー",
 nameI18n:{"ja":"ミノー","en":"Minnow","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"静川",
 locationI18n:{"ja":"静川","en":"Calm River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/007.PNG"
},
{
 name:"ティラピア",
 nameI18n:{"ja":"ティラピア","en":"Tilapia","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"青",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"川(青魚影)",
 locationI18n:{"ja":"川(青魚影)","en":"River (Blue Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/008.PNG"
},
{
 name:"テンチ",
 nameI18n:{"ja":"テンチ","en":"Tench","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/009.PNG"
},
{
 name:"ホワイトフィッシュ",
 nameI18n:{"ja":"ホワイトフィッシュ","en":"Whitefish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"中",
 price:105,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/010.PNG"
},
{
 name:"マブナ",
 nameI18n:{"ja":"マブナ","en":"Crucian Carp","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"中",
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/011.PNG"
},
{
 name:"ブリーク",
 nameI18n:{"ja":"ブリーク","en":"Bleak","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"湖",
 locationI18n:{"ja":"湖","en":"Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/012.PNG"
},
{
 name:"シュナイダー",
 nameI18n:{"ja":"シュナイダー","en":"Schneider","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/013.PNG"
},
{
 name:"コウライエビ",
 nameI18n:{"ja":"コウライエビ","en":"Fleshy Prawn","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"川",
 locationI18n:{"ja":"川","en":"River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/014.PNG"
},
{
 name:"ニシイワシ",
 nameI18n:{"ja":"ニシイワシ","en":"Sardine","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海",
 locationI18n:{"ja":"海","en":"Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/015.PNG"
},
{
 name:"スズキ",
 nameI18n:{"ja":"スズキ","en":"Japanese Seabass","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"中",
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海",
 locationI18n:{"ja":"海","en":"Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/016.PNG"
},
{
 name:"カツオ",
 nameI18n:{"ja":"カツオ","en":"Skipjack Tuna","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"大",
 price:210,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海",
 locationI18n:{"ja":"海","en":"Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/017.PNG"
},
{
 name:"タチウオ",
 nameI18n:{"ja":"タチウオ","en":"Largehead Hairtail","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"大",
 price:105,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/018.PNG"
},
{
 name:"ウミエビ",
 nameI18n:{"ja":"ウミエビ","en":"Slipper Lobster","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/019.PNG"
},
{
 name:"マアジ",
 nameI18n:{"ja":"マアジ","en":"Japanese Jack Mackerel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/020.PNG"
},
{
 name:"カイブツギンザメ",
 nameI18n:{"ja":"カイブツギンザメ","en":"Giant Chimaera","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"青",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海(青魚影)",
 locationI18n:{"ja":"海(青魚影)","en":"Sea (Blue Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/021.PNG"
},
{
 name:"ウミトゲウオ",
 nameI18n:{"ja":"ウミトゲウオ","en":"Sea Stickleback","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:50,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/022.PNG"
},
{
 name:"ストライプトレッドマレット",
 nameI18n:{"ja":"ストライプトレッドマレット","en":"Striped Red Mullet","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"金",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/023.PNG"
},
{
 name:"イシドジョウ",
 nameI18n:{"ja":"イシドジョウ","en":"Stone Loach","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/024.PNG"
},
{
 name:"マッドサンフィッシュ",
 nameI18n:{"ja":"マッドサンフィッシュ","en":"Mud Sunfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/025.PNG"
},
{
 name:"キュウリウオ",
 nameI18n:{"ja":"キュウリウオ","en":"Smelt","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/026.PNG"
},
{
 name:"ラッフ",
 nameI18n:{"ja":"ラッフ","en":"Ruffe","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/027.PNG"
},
{
 name:"フランスアジ",
 nameI18n:{"ja":"フランスアジ","en":"French Jack Mackerel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 shadow:"中",
 price:155,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/028.PNG"
},
{
 name:"タツノオトシゴ",
 nameI18n:{"ja":"タツノオトシゴ","en":"Seahorse","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","0-6"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/029.PNG"
},
{
 name:"アンコウ",
 nameI18n:{"ja":"アンコウ","en":"Monkfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 shadow:"金",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/030.PNG"
},
{
 name:"イガイ",
 nameI18n:{"ja":"イガイ","en":"Mussel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"小",
 price:100,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/031.PNG"
},
{
 name:"パイクパーチ",
 nameI18n:{"ja":"パイクパーチ","en":"Pikeperch","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"中",
 price:230,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巨木の川",
 locationI18n:{"ja":"巨木の川","en":"Giant Tree River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/032.PNG"
},
{
 name:"オタマジャクシ",
 nameI18n:{"ja":"オタマジャクシ","en":"Tadpole","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"小",
 price:100,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/033.PNG"
},
{
 name:"北欧アカザエビ",
 nameI18n:{"ja":"北欧アカザエビ","en":"Nordic Norway Lobster","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","18-0","0-6"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/034.PNG"
},
{
 name:"マダコ",
 nameI18n:{"ja":"マダコ","en":"Common Octopus","zh-CN":"","zh-TW":"","ko":"","th":""}, 
 level:4,
 shadow:"金",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/035.PNG"
},
{
 name:"タイセイヨウサケ",
 nameI18n:{"ja":"タイセイヨウサケ","en":"Atlantic Salmon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"中",
 price:155,
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0","0-6"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/036.PNG"
},
{
 name:"ピグミータコ",
 nameI18n:{"ja":"ピグミータコ","en":"Pygmy Octopus","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 shadow:"小",
 price:150,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/037.PNG"
},
{
 name:"ヤドカリ",
 nameI18n:{"ja":"ヤドカリ","en":"Hermit Crab","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/038.PNG"
},
{
 name:"カクレクマノミ",
 nameI18n:{"ja":"カクレクマノミ","en":"Clownfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/039.PNG"
},
{
 name:"オオクチバス",
 nameI18n:{"ja":"オオクチバス","en":"Largemouth Bass","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"中",
 price:230,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/040.PNG"
},
{
 name:"ヨーロッパコイ",
 nameI18n:{"ja":"ヨーロッパコイ","en":"European Carp","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"中",
 price:230,
 weather:["晴れ","虹"],
 time:["12-18","18-0"],
 location:"霞川",
 locationI18n:{"ja":"霞川","en":"Mist River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/041.PNG"
},
{
 name:"カワメンタイ",
 nameI18n:{"ja":"カワメンタイ","en":"Burbot","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"中",
 price:230,
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0"],
 location:"静川",
 locationI18n:{"ja":"静川","en":"Calm River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/042.PNG"
},
{
 name:"ハゼ",
 nameI18n:{"ja":"ハゼ","en":"Goby","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"小",
 price:150,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/043.PNG"
},
{
 name:"サワガニ",
 nameI18n:{"ja":"サワガニ","en":"Japanese Freshwater Crab","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/044.PNG"
},
{
 name:"イシビラメ",
 nameI18n:{"ja":"イシビラメ","en":"Turbot","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 shadow:"金",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/045.PNG"
},
{
 name:"ヨーロッパヒラメ",
 nameI18n:{"ja":"ヨーロッパヒラメ","en":"European Plaice","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"中",
 price:230,
 weather:["晴れ","雨","虹"],
 time:["18-0","0-6"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/046.PNG"
},
{
 name:"レッドベリーピラニア",
 nameI18n:{"ja":"レッドベリーピラニア","en":"Red-bellied Piranha","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"中",
 price:230,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巨木の川",
 locationI18n:{"ja":"巨木の川","en":"Giant Tree River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/047.PNG"
},
{
 name:"バタフライコイ",
 nameI18n:{"ja":"バタフライコイ","en":"Butterfly Koi","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 shadow:"大",
 price:320,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/048.PNG"
},
{
 name:"カワギンポ",
 nameI18n:{"ja":"カワギンポ","en":"River Blenny","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 shadow:"小",
 price:150,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"霞川",
 locationI18n:{"ja":"霞川","en":"Mist River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/049.PNG"
},
{
 name:"マス",
 nameI18n:{"ja":"マス","en":"Trout","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 shadow:"中",
 price:230,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/050.PNG"
},
{
 name:"ラッド",
 nameI18n:{"ja":"ラッド","en":"Rudd","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 shadow:"小",
 price:150,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/051.PNG"
},
{
 name:"タイセイヨウサバ",
 nameI18n:{"ja":"タイセイヨウサバ","en":"Atlantic Mackerel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 shadow:"小",
 price:150,
 weather:["晴れ","虹"],
 time:["12-18","18-0"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/052.PNG"
},
{
 name:"ヨーロッパロブスター",
 nameI18n:{"ja":"ヨーロッパロブスター","en":"European Lobster","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 shadow:"中",
 price:230,
 weather:["晴れ","雨","虹"],
 time:["18-0","0-6"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/053.PNG"
},
{
 name:"ヨーロッパスルメイカ",
 nameI18n:{"ja":"ヨーロッパスルメイカ","en":"European Squid","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 shadow:"金",
 price:320,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/054.PNG"
},
{
 name:"シンジュガイ",
 nameI18n:{"ja":"シンジュガイ","en":"Pearl Mussel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 shadow:"中",
 price:380,
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/055.PNG"
},
{
 name:"フグ",
 nameI18n:{"ja":"フグ","en":"Pufferfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 shadow:"中",
 price:230,
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/056.PNG"
},
{
 name:"シロザケ",
 nameI18n:{"ja":"シロザケ","en":"Chum Salmon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 shadow:"小",
 price:150,
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"静川",
 locationI18n:{"ja":"静川","en":"Calm River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/057.PNG"
},
{
 name:"カワヒメマス",
 nameI18n:{"ja":"カワヒメマス","en":"Kokanee Salmon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 shadow:"中",
 price:230,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/058.PNG"
},
{
 name:"タブ・ガーナード",
 nameI18n:{"ja":"タブ・ガーナード","en":"Tub Gurnard","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 shadow:"中",
 price:380,
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/059.PNG"
},
{
 name:"ネコザメ",
 nameI18n:{"ja":"ネコザメ","en":"Bullhead Shark","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 shadow:"金",
 price:535,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/060.PNG"
},
{
 name:"イトヨ",
 nameI18n:{"ja":"イトヨ","en":"Three-spined Stickleback","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 shadow:"小",
 price:150,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"浅水川",
 locationI18n:{"ja":"浅水川","en":"Shallow River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/061.PNG"
},
{
 name:"アプロケイルス",
 nameI18n:{"ja":"アプロケイルス","en":"Aplocheilus Killifish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 shadow:"小",
 price:150,
 weather:["晴れ","虹"],
 time:["12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/062.PNG"
},
{
 name:"カジカ",
 nameI18n:{"ja":"カジカ","en":"Sculpin","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 shadow:"小",
 price:150,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/063.PNG"
},
{
 name:"リュウグウノツカイ",
 nameI18n:{"ja":"リュウグウノツカイ","en":"Oarfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 shadow:"金",
 price:535,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/064.PNG"
},
{
 name:"スペインダイ",
 nameI18n:{"ja":"スペインダイ","en":"Spanish Bream","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 shadow:"中",
 price:230,
 weather:["雨","虹"],
 time:["18-0","0-6"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/065.PNG"
},
{
 name:"ヨーロッパウナギ",
 nameI18n:{"ja":"ヨーロッパウナギ","en":"European Eel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 shadow:"中",
 price:380,
 weather:["虹"],
 time:["6-12","12-18","18-0"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/066.PNG"
},
{
 name:"黄金タラバガニ",
 nameI18n:{"ja":"黄金タラバガニ","en":"Golden King Crab","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 shadow:"金",
 price:850,
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/067.PNG"
},
{
 name:"マッドミノー",
 nameI18n:{"ja":"マッドミノー","en":"Mudminnow","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 shadow:"小",
 price:250,
 weather:["晴れ","虹"],
 time:["6-12","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/068.PNG"
},
{
 name:"北欧ブルーアカザエビ",
 nameI18n:{"ja":"北欧ブルーアカザエビ","en":"Nordic Blue Norway Lobster","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 shadow:"小",
 price:250,
 weather:["晴れ","雨","虹"],
 time:["18-0","0-6"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/069.PNG"
},
{
 name:"キンギョ",
 nameI18n:{"ja":"キンギョ","en":"Goldfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 shadow:"小",
 price:250,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/070.PNG"
},
{
 name:"タラバガニ",
 nameI18n:{"ja":"タラバガニ","en":"King Crab","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 shadow:"大",
 price:535,
 weather:["虹"],
 time:["6-12","12-18","18-0"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/071.PNG"
},
{
 name:"モンツキダラ",
 nameI18n:{"ja":"モンツキダラ","en":"Haddock","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 shadow:"中",
 price:230,
 weather:["晴れ","虹"],
 time:["12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/072.PNG"
},
{
 name:"ノーザンパイク",
 nameI18n:{"ja":"ノーザンパイク","en":"Northern Pike","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 shadow:"中",
 price:610,
 weather:["雨","虹"],
 time:["18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/073.PNG"
},
{
 name:"パンプキンシード",
 nameI18n:{"ja":"パンプキンシード","en":"Pumpkinseed","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 shadow:"小",
 price:250,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/074.PNG"
},
{
 name:"ドナウイトウ",
 nameI18n:{"ja":"ドナウイトウ","en":"Danube Huchen","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 shadow:"中",
 price:380,
 weather:["虹"],
 time:["12-18","18-0","0-6"],
 location:"巨木の川",
 locationI18n:{"ja":"巨木の川","en":"Giant Tree River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/075.PNG"
},
{
 name:"ミナミマグロ",
 nameI18n:{"ja":"ミナミマグロ","en":"Southern Bluefin Tuna","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 shadow:"大",
 price:850,
 weather:["虹"],
 time:["6-12","12-18"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/076.PNG"
},
{
 name:"マンボウ",
 nameI18n:{"ja":"マンボウ","en":"Ocean Sunfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 shadow:"大",
 price:850,
 weather:["晴れ","雨","虹"],
 time:["6-12","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/077.PNG"
},
{
 name:"アカマンボウ",
 nameI18n:{"ja":"アカマンボウ","en":"Opah","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 shadow:"大",
 price:850,
 weather:["晴れ","雨","虹"],
 time:["18-0","0-6"],
 location:"海釣りクエスト(金魚影)",
 locationI18n:{"ja":"海釣りクエスト(金魚影)","en":"Sea Fishing Quest (Gold Shadow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/078.PNG"
},
{
 name:"ヨーロッパナマズ",
 nameI18n:{"ja":"ヨーロッパナマズ","en":"Wels Catfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 shadow:"中",
 price:610,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/079.PNG"
},
{
 name:"ブルーギル",
 nameI18n:{"ja":"ブルーギル","en":"Bluegill","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 shadow:"小",
 price:395,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/080.PNG"
},
{
 name:"ホッキョクイワナ",
 nameI18n:{"ja":"ホッキョクイワナ","en":"Arctic Char","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 shadow:"中",
 price:610,
 weather:["雨","虹"],
 time:["12-18","18-0"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/081.PNG"
},
{
 name:"メカジキ",
 nameI18n:{"ja":"メカジキ","en":"Swordfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 shadow:"大",
 price:850,
 weather:["虹"],
 time:["6-12","12-18"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/082.PNG"
},
{
 name:"シュモクザメ",
 nameI18n:{"ja":"シュモクザメ","en":"Hammerhead Shark","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 shadow:"大",
 price:850,
 weather:["虹"],
 time:["18-0","0-6"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/083.PNG"
},
{
 name:"アオザメ",
 nameI18n:{"ja":"アオザメ","en":"Shortfin Mako Shark","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 shadow:"金",
 price:850,
 weather:["虹"],
 time:["6-12","12-18"],
 location:"海釣りクエスト",
 locationI18n:{"ja":"海釣りクエスト","en":"Sea Fishing Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/084.PNG"
},
{
 name:"アジアアロワナ",
 nameI18n:{"ja":"アジアアロワナ","en":"Asian Arowana","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 shadow:"小",
 price:395,
 weather:["虹"],
 time:["6-12","12-18","0-6"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ライオンヘッド",
 nameI18n:{"ja":"ライオンヘッド","en":"Lionhead Goldfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 shadow:"中",
 price:395,
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"シマスズメダイ",
 nameI18n:{"ja":"シマスズメダイ","en":"Sergeant Major Damselfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 shadow:"中",
 price:610,
 weather:["晴れ","虹"],
 time:["12-18","18-0"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ジンベエザメ",
 nameI18n:{"ja":"ジンベエザメ","en":"Whale Shark","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 shadow:"金",
 price:850,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"海釣りクエスト",
 locationI18n:{"ja":"海釣りクエスト","en":"Sea Fishing Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ベタ",
 nameI18n:{"ja":"ベタ","en":"Betta","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 shadow:"小",
 price:395,
 weather:["雨","虹"],
 time:["12-18","18-0"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"エンゼルフィッシュ",
 nameI18n:{"ja":"エンゼルフィッシュ","en":"Angelfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 shadow:"中",
 price:610,
 weather:["虹"],
 time:["18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"シイラ",
 nameI18n:{"ja":"シイラ","en":"Mahi-mahi","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 shadow:"大",
 price:850,
 weather:["虹"],
 time:["6-12","12-18"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"アオウミガメ",
 nameI18n:{"ja":"アオウミガメ","en":"Green Sea Turtle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 shadow:"大",
 price:850,
 weather:["虹"],
 time:["12-18","18-0"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ミズクラゲ",
 nameI18n:{"ja":"ミズクラゲ","en":"Moon Jellyfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 shadow:"金",
 price:850,
 weather:["雨","虹"],
 time:["12-18","18-0","0-6"],
 location:"海釣りクエスト",
 locationI18n:{"ja":"海釣りクエスト","en":"Sea Fishing Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ニザダイ",
 nameI18n:{"ja":"ニザダイ","en":"Surgeonfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:13,
 shadow:"中",
 weather:["雨","虹"],
 time:["12-18","18-0","0-6"],
 location:"旧海",
 locationI18n:{"ja":"旧海","en":"Old Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ミノカサゴ",
 nameI18n:{"ja":"ミノカサゴ","en":"Lionfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:13,
 shadow:"中",
 weather:["雨","虹"],
 time:["6-12","0-6"],
 location:"クジラ海",
 locationI18n:{"ja":"クジラ海","en":"Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"シリキルリスズメダイ",
 nameI18n:{"ja":"シリキルリスズメダイ","en":"Yellowtail Blue Damselfish","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:14,
 shadow:"小",
 weather:["晴れ","虹"],
 time:["12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"レナーズラス",
 nameI18n:{"ja":"レナーズラス","en":"Rainbow Wrasse","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:14,
 shadow:"中",
 weather:["晴れ","虹"],
 time:["12-18","18-0"],
 location:"そよ風の海",
 locationI18n:{"ja":"そよ風の海","en":"Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"積み木カクレクマノミ(青)",
 nameI18n:{"ja":"積み木カクレクマノミ(青)","en":"Building Block Clownfish (Blue)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/1001.PNG",
 auth:false
},
{
 name:"積み木カクレクマノミ(赤)",
 nameI18n:{"ja":"積み木カクレクマノミ(赤)","en":"Building Block Clownfish (Red)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/1002.PNG",
 auth:false
},
{
 name:"積み木カクレクマノミ(青緑)",
 nameI18n:{"ja":"積み木カクレクマノミ(青緑)","en":"Building Block Clownfish (Teal)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/1003.PNG",
 auth:false
},
{
 name:"積み木カクレクマノミ(紫)",
 nameI18n:{"ja":"積み木カクレクマノミ(紫)","en":"Building Block Clownfish (Purple)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 shadow:"小",
 price:100,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/1004.PNG",
 auth:false
},
{
 name:"積み木カクレクマノミ(虹)",
 nameI18n:{"ja":"積み木カクレクマノミ(虹)","en":"Building Block Clownfish (Rainbow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 shadow:"小",
 price:150,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海",
 locationI18n:{"ja":"東海","en":"East Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"fish/1005.PNG",
 auth:false
}
  // ここに追加していく
].map((c,i) => ({
  ...c,
  type:"fish",
  bookIndex:i
}));
