// トレンド商店データ
// category    : "fashion" | "furniture" | "other"
// subcategory : fashionのみ使用（hat/top/bottom/setup/shoes/accessory/petCostume）
// limit       : 購入上限数。null = 上限無し
// season      : シーズンを識別するID。終了判定・表示グループ分けに使用

const shopData = [
  {
    id: 1,
    category: "fashion",
    subcategory: "hat",
    name: "アザラシのベレー帽",
    nameI18n: {"ja":"アザラシのベレー帽","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/001.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 2,
    category: "fashion",
    subcategory: "hat",
    name: "サカバンバスピスのベレー帽",
    nameI18n: {"ja":"サカバンバスピスのベレー帽","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/002.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 3,
    category: "fashion",
    subcategory: "hat",
    name: "カエルのシャワーキャップ",
    nameI18n: {"ja":"カエルのシャワーキャップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/003.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 4,
    category: "fashion",
    subcategory: "hat",
    name: "クジラのシャワーキャップ",
    nameI18n: {"ja":"クジラのシャワーキャップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/004.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 5,
    category: "fashion",
    subcategory: "hat",
    name: "クジラのシャワーキャップ",
    nameI18n: {"ja":"クジラのシャワーキャップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/005.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 6,
    category: "fashion",
    subcategory: "hat",
    name: "ヒトデのお花頭飾り",
    nameI18n: {"ja":"ヒトデのお花頭飾り","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/006.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 7,
    category: "fashion",
    subcategory: "hat",
    name: "ヒトデのお花頭飾り",
    nameI18n: {"ja":"ヒトデのお花頭飾り","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/007.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 8,
    category: "fashion",
    subcategory: "hat",
    name: "ヒトデのお花頭飾り",
    nameI18n: {"ja":"ヒトデのお花頭飾り","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/008.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 9,
    category: "fashion",
    subcategory: "hat",
    name: "リボン付きセーラー帽",
    nameI18n: {"ja":"リボン付きセーラー帽","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/009.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 10,
    category: "fashion",
    subcategory: "hat",
    name: "リボン付きセーラー帽",
    nameI18n: {"ja":"リボン付きセーラー帽","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/010.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 11,
    category: "fashion",
    subcategory: "hat",
    name: "リボン付きセーラー帽",
    nameI18n: {"ja":"リボン付きセーラー帽","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/011.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 12,
    category: "fashion",
    subcategory: "hat",
    name: "エビフライ帽子",
    nameI18n: {"ja":"エビフライ帽子","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/012.PNG",
    price: 3080,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 13,
    category: "fashion",
    subcategory: "hat",
    name: "エビフライ帽子",
    nameI18n: {"ja":"エビフライ帽子","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/013.PNG",
    price: 3080,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 14,
    category: "fashion",
    subcategory: "hat",
    name: "エビフライ帽子",
    nameI18n: {"ja":"エビフライ帽子","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/014.PNG",
    price: 3080,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 15,
    category: "fashion",
    subcategory: "hat",
    name: "エビフライ帽子",
    nameI18n: {"ja":"エビフライ帽子","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/015.PNG",
    price: 3080,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 16,
    category: "fashion",
    subcategory: "hat",
    name: "エビフライ帽子",
    nameI18n: {"ja":"エビフライ帽子","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/016.PNG",
    price: 3080,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 17,
    category: "fashion",
    subcategory: "hat",
    name: "エビフライ帽子",
    nameI18n: {"ja":"エビフライ帽子","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/017.PNG",
    price: 3080,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 18,
    category: "fashion",
    subcategory: "hat",
    name: "貝殻のバンダナ",
    nameI18n: {"ja":"貝殻のバンダナ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/018.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 19,
    category: "fashion",
    subcategory: "hat",
    name: "貝殻のバンダナ",
    nameI18n: {"ja":"貝殻のバンダナ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/019.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 20,
    category: "fashion",
    subcategory: "hat",
    name: "貝殻のバンダナ",
    nameI18n: {"ja":"貝殻のバンダナ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/020.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 21,
    category: "fashion",
    subcategory: "hat",
    name: "ヒトデの波模様バンダナ",
    nameI18n: {"ja":"ヒトデの波模様バンダナ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/021.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 22,
    category: "fashion",
    subcategory: "hat",
    name: "ヒトデの波模様バンダナ",
    nameI18n: {"ja":"ヒトデの波模様バンダナ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/022.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 23,
    category: "fashion",
    subcategory: "hat",
    name: "ヒトデの波模様バンダナ",
    nameI18n: {"ja":"ヒトデの波模様バンダナ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/023.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 24,
    category: "fashion",
    subcategory: "top",
    name: "花柄襟付きノースリーブ",
    nameI18n: {"ja":"花柄襟付きノースリーブ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/024.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 25,
    category: "fashion",
    subcategory: "top",
    name: "アイスクリームの縞柄ノースリーブ",
    nameI18n: {"ja":"アイスクリームの縞柄ノースリーブ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/025.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 26,
    category: "fashion",
    subcategory: "top",
    name: "花のビーチシャツ",
    nameI18n: {"ja":"花のビーチシャツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/026.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 27,
    category: "fashion",
    subcategory: "top",
    name: "縞柄プリントシャツ",
    nameI18n: {"ja":"縞柄プリントシャツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/027.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 28,
    category: "fashion",
    subcategory: "top",
    name: "魚の波模様シャツ",
    nameI18n: {"ja":"魚の波模様シャツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/028.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 29,
    category: "fashion",
    subcategory: "top",
    name: "細リボンキャミソール",
    nameI18n: {"ja":"細リボンキャミソール","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/029.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 30,
    category: "fashion",
    subcategory: "top",
    name: "細リボンキャミソール",
    nameI18n: {"ja":"細リボンキャミソール","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/030.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 31,
    category: "fashion",
    subcategory: "top",
    name: "太リボンキャミソール",
    nameI18n: {"ja":"太リボンキャミソール","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/031.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 32,
    category: "fashion",
    subcategory: "top",
    name: "太リボンキャミソール",
    nameI18n: {"ja":"太リボンキャミソール","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/032.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 33,
    category: "fashion",
    subcategory: "top",
    name: "リボン付きセーラー服",
    nameI18n: {"ja":"リボン付きセーラー服","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/033.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 34,
    category: "fashion",
    subcategory: "top",
    name: "縞柄入りセーラー服",
    nameI18n: {"ja":"縞柄入りセーラー服","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/034.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 35,
    category: "fashion",
    subcategory: "top",
    name: "ダブルリボンセーラー服",
    nameI18n: {"ja":"ダブルリボンセーラー服","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/035.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 36,
    category: "fashion",
    subcategory: "top",
    name: "タツノオトシゴのレースキャミソール",
    nameI18n: {"ja":"タツノオトシゴのレースキャミソール","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/036.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 37,
    category: "fashion",
    subcategory: "top",
    name: "フグのレースキャミソール",
    nameI18n: {"ja":"フグのレースキャミソール","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/037.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 38,
    category: "fashion",
    subcategory: "top",
    name: "貝殻レースのレイヤード風半袖トップス",
    nameI18n: {"ja":"貝殻レースのレイヤード風半袖トップス","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/038.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 39,
    category: "fashion",
    subcategory: "top",
    name: "貝殻レースのレイヤード風半袖トップス",
    nameI18n: {"ja":"貝殻レースのレイヤード風半袖トップス","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/039.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 40,
    category: "fashion",
    subcategory: "top",
    name: "真珠貝レースの半袖トップス",
    nameI18n: {"ja":"真珠貝レースの半袖トップス","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/040.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 41,
    category: "fashion",
    subcategory: "top",
    name: "真珠貝レースの半袖トップス",
    nameI18n: {"ja":"真珠貝レースの半袖トップス","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/041.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 42,
    category: "fashion",
    subcategory: "top",
    name: "魚のカジュアルジャケット",
    nameI18n: {"ja":"魚のカジュアルジャケット","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/042.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 43,
    category: "fashion",
    subcategory: "top",
    name: "魚のカジュアルジャケット",
    nameI18n: {"ja":"魚のカジュアルジャケット","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/043.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 44,
    category: "fashion",
    subcategory: "bottom",
    name: "ビーチハーフパンツ",
    nameI18n: {"ja":"ビーチハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/044.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 45,
    category: "fashion",
    subcategory: "bottom",
    name: "ビーチハーフパンツ",
    nameI18n: {"ja":"ビーチハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/045.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 46,
    category: "fashion",
    subcategory: "bottom",
    name: "リボン付きプリーツスカート",
    nameI18n: {"ja":"リボン付きプリーツスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/046.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 47,
    category: "fashion",
    subcategory: "bottom",
    name: "縞柄入りプリーツスカート",
    nameI18n: {"ja":"縞柄入りプリーツスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/047.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 48,
    category: "fashion",
    subcategory: "bottom",
    name: "ボタン付きプリーツスカート",
    nameI18n: {"ja":"ボタン付きプリーツスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/048.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 49,
    category: "fashion",
    subcategory: "bottom",
    name: "リボン付きチェック柄ロングスカート",
    nameI18n: {"ja":"リボン付きチェック柄ロングスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/049.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 50,
    category: "fashion",
    subcategory: "bottom",
    name: "リボン付きチェック柄ロングスカート",
    nameI18n: {"ja":"リボン付きチェック柄ロングスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/050.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 51,
    category: "fashion",
    subcategory: "bottom",
    name: "うろこ柄ロングスカート",
    nameI18n: {"ja":"うろこ柄ロングスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/051.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 52,
    category: "fashion",
    subcategory: "bottom",
    name: "うろこ柄ロングスカート",
    nameI18n: {"ja":"うろこ柄ロングスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/052.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 53,
    category: "fashion",
    subcategory: "bottom",
    name: "フリル付きハーフパンツ",
    nameI18n: {"ja":"フリル付きハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/053.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 54,
    category: "fashion",
    subcategory: "bottom",
    name: "フリル付きハーフパンツ",
    nameI18n: {"ja":"フリル付きハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/054.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 55,
    category: "fashion",
    subcategory: "bottom",
    name: "レースアップハーフパンツ",
    nameI18n: {"ja":"レースアップハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/055.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 56,
    category: "fashion",
    subcategory: "bottom",
    name: "レースアップハーフパンツ",
    nameI18n: {"ja":"レースアップハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/056.PNG",
    price: 1230,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 57,
    category: "fashion",
    subcategory: "bottom",
    name: "タツノオトシゴのレースパジャマズボン",
    nameI18n: {"ja":"タツノオトシゴのレースパジャマズボン","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/057.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 58,
    category: "fashion",
    subcategory: "bottom",
    name: "フグのレースパジャマズボン",
    nameI18n: {"ja":"フグのレースパジャマズボン","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/058.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 59,
    category: "fashion",
    subcategory: "bottom",
    name: "貝殻のレースドレープパンツ",
    nameI18n: {"ja":"貝殻のレースドレープパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/059.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 60,
    category: "fashion",
    subcategory: "bottom",
    name: "貝殻のレースドレープパンツ",
    nameI18n: {"ja":"貝殻のレースドレープパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/060.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 61,
    category: "fashion",
    subcategory: "bottom",
    name: "縞柄入りワークハーフパンツ",
    nameI18n: {"ja":"縞柄入りワークハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/061.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 62,
    category: "fashion",
    subcategory: "bottom",
    name: "ウェーブ柄入りワークハーフパンツ",
    nameI18n: {"ja":"ウェーブ柄入りワークハーフパンツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/062.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 63,
    category: "fashion",
    subcategory: "setup",
    name: "ゆるTプリーツスカート",
    nameI18n: {"ja":"ゆるTプリーツスカート","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/063.PNG",
    price: 2520,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 64,
    category: "fashion",
    subcategory: "shoes",
    name: "うろこ柄レインブーツ",
    nameI18n: {"ja":"うろこ柄レインブーツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/141.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 65,
    category: "fashion",
    subcategory: "shoes",
    name: "うろこ柄レインブーツ",
    nameI18n: {"ja":"うろこ柄レインブーツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/142.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 66,
    category: "fashion",
    subcategory: "shoes",
    name: "ビーチレインブーツ",
    nameI18n: {"ja":"ビーチレインブーツ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/143.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 67,
    category: "fashion",
    subcategory: "shoes",
    name: "魚のスリッパ",
    nameI18n: {"ja":"魚のスリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/144.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 68,
    category: "fashion",
    subcategory: "shoes",
    name: "魚のスリッパ",
    nameI18n: {"ja":"魚のスリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/145.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 69,
    category: "fashion",
    subcategory: "shoes",
    name: "ウェーブ柄レザースリッパ",
    nameI18n: {"ja":"ウェーブ柄レザースリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/146.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 70,
    category: "fashion",
    subcategory: "shoes",
    name: "ウェーブ柄レザースリッパ",
    nameI18n: {"ja":"ウェーブ柄レザースリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/147.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 71,
    category: "fashion",
    subcategory: "shoes",
    name: "ウェーブ柄レザースリッパ",
    nameI18n: {"ja":"ウェーブ柄レザースリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/148.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 72,
    category: "fashion",
    subcategory: "shoes",
    name: "ゴムバンド付きカジュアルシューズ",
    nameI18n: {"ja":"ゴムバンド付きカジュアルシューズ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/149.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 73,
    category: "fashion",
    subcategory: "shoes",
    name: "ゴムバンド付きカジュアルシューズ",
    nameI18n: {"ja":"ゴムバンド付きカジュアルシューズ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/150.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 74,
    category: "fashion",
    subcategory: "shoes",
    name: "ゴムバンド付きカジュアルシューズ",
    nameI18n: {"ja":"ゴムバンド付きカジュアルシューズ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/151.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 75,
    category: "fashion",
    subcategory: "shoes",
    name: "うろこ柄スリッパ",
    nameI18n: {"ja":"うろこ柄スリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/152.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 76,
    category: "fashion",
    subcategory: "shoes",
    name: "タツノオトシゴのスリッパ",
    nameI18n: {"ja":"タツノオトシゴのスリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/153.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 77,
    category: "fashion",
    subcategory: "shoes",
    name: "フグのスリッパ",
    nameI18n: {"ja":"フグのスリッパ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/154.PNG",
    price: 1400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 78,
    category: "fashion",
    subcategory: "accessory",
    name: "ちびタコの絆創膏",
    nameI18n: {"ja":"ちびタコの絆創膏","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/064.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 79,
    category: "fashion",
    subcategory: "accessory",
    name: "ちびタコの絆創膏",
    nameI18n: {"ja":"ちびタコの絆創膏","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/065.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 80,
    category: "fashion",
    subcategory: "accessory",
    name: "ちびタコの絆創膏",
    nameI18n: {"ja":"ちびタコの絆創膏","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/066.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 81,
    category: "fashion",
    subcategory: "accessory",
    name: "貝殻のペロペロキャンディ",
    nameI18n: {"ja":"貝殻のペロペロキャンディ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/067.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 82,
    category: "fashion",
    subcategory: "accessory",
    name: "貝殻のペロペロキャンディ",
    nameI18n: {"ja":"貝殻のペロペロキャンディ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/068.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 83,
    category: "fashion",
    subcategory: "accessory",
    name: "貝殻のペロペロキャンディ",
    nameI18n: {"ja":"貝殻のペロペロキャンディ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/069.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 84,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチサングラス",
    nameI18n: {"ja":"ビーチサングラス","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/070.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 85,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチサングラス",
    nameI18n: {"ja":"ビーチサングラス","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/071.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 86,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチサングラス",
    nameI18n: {"ja":"ビーチサングラス","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/072.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 87,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチフラワーショルダーバッグ",
    nameI18n: {"ja":"ビーチフラワーショルダーバッグ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/073.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 88,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチフラワーショルダーバッグ",
    nameI18n: {"ja":"ビーチフラワーショルダーバッグ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/074.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 89,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチフラワーショルダーバッグ",
    nameI18n: {"ja":"ビーチフラワーショルダーバッグ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/075.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 90,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチフラワーショルダーバッグ",
    nameI18n: {"ja":"ビーチフラワーショルダーバッグ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/076.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 91,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチフラワーショルダーバッグ",
    nameI18n: {"ja":"ビーチフラワーショルダーバッグ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/077.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 92,
    category: "fashion",
    subcategory: "accessory",
    name: "ビーチフラワーショルダーバッグ",
    nameI18n: {"ja":"ビーチフラワーショルダーバッグ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/078.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 93,
    category: "fashion",
    subcategory: "petCostume",
    name: "ちびタコの被り物",
    nameI18n: {"ja":"ちびタコの被り物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/079.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 94,
    category: "fashion",
    subcategory: "petCostume",
    name: "ちびタコの被り物",
    nameI18n: {"ja":"ちびタコの被り物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/080.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 95,
    category: "fashion",
    subcategory: "petCostume",
    name: "ちびタコの被り物",
    nameI18n: {"ja":"ちびタコの被り物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/081.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 96,
    category: "fashion",
    subcategory: "petCostume",
    name: "おおぐち魚のしっぽ飾り",
    nameI18n: {"ja":"おおぐち魚のしっぽ飾り","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/082.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 97,
    category: "fashion",
    subcategory: "petCostume",
    name: "おおぐち魚のしっぽ飾り",
    nameI18n: {"ja":"おおぐち魚のしっぽ飾り","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/083.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 98,
    category: "fashion",
    subcategory: "petCostume",
    name: "おおぐち魚のしっぽ飾り",
    nameI18n: {"ja":"おおぐち魚のしっぽ飾り","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/084.PNG",
    price: 7000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 99,
    category: "furniture",
    subcategory: null,
    name: "ちびタコの置物",
    nameI18n: {"ja":"ちびタコの置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/085.PNG",
    price: 1520,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 100,
    category: "furniture",
    subcategory: null,
    name: "ちびタコの置物",
    nameI18n: {"ja":"ちびタコの置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/086.PNG",
    price: 1520,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 101,
    category: "furniture",
    subcategory: null,
    name: "ちびタコの置物",
    nameI18n: {"ja":"ちびタコの置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/087.PNG",
    price: 1520,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 102,
    category: "furniture",
    subcategory: null,
    name: "サカバンバスピスのチェア",
    nameI18n: {"ja":"サカバンバスピスのチェア","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/088.PNG",
    price: 1520,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 103,
    category: "furniture",
    subcategory: null,
    name: "リーフ＆フラワーの浮き輪",
    nameI18n: {"ja":"リーフ＆フラワーの浮き輪","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/089.PNG",
    price: 2200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 104,
    category: "furniture",
    subcategory: null,
    name: "リーフ＆フラワーの浮き輪",
    nameI18n: {"ja":"リーフ＆フラワーの浮き輪","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/090.PNG",
    price: 2200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 105,
    category: "furniture",
    subcategory: null,
    name: "リーフ＆フラワーの浮き輪",
    nameI18n: {"ja":"リーフ＆フラワーの浮き輪","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/091.PNG",
    price: 2200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 106,
    category: "furniture",
    subcategory: null,
    name: "ちびタコの浮き輪",
    nameI18n: {"ja":"ちびタコの浮き輪","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/092.PNG",
    price: 2200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 107,
    category: "furniture",
    subcategory: null,
    name: "ちびタコの浮き輪",
    nameI18n: {"ja":"ちびタコの浮き輪","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/093.PNG",
    price: 2200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 108,
    category: "furniture",
    subcategory: null,
    name: "ちびタコの浮き輪",
    nameI18n: {"ja":"ちびタコの浮き輪","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/094.PNG",
    price: 2200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 109,
    category: "furniture",
    subcategory: null,
    name: "うろこ柄のダイニングチェア",
    nameI18n: {"ja":"うろこ柄のダイニングチェア","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/095.PNG",
    price: 880,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 110,
    category: "furniture",
    subcategory: null,
    name: "ウェーブダイニングチェア",
    nameI18n: {"ja":"ウェーブダイニングチェア","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/096.PNG",
    price: 880,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 111,
    category: "furniture",
    subcategory: null,
    name: "ヒトデの円形テーブル",
    nameI18n: {"ja":"ヒトデの円形テーブル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/097.PNG",
    price: 750,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 112,
    category: "furniture",
    subcategory: null,
    name: "貝殻の円形テーブル",
    nameI18n: {"ja":"貝殻の円形テーブル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/098.PNG",
    price: 750,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 113,
    category: "furniture",
    subcategory: null,
    name: "貝殻の食器棚",
    nameI18n: {"ja":"貝殻の食器棚","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/099.PNG",
    price: 1000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 114,
    category: "furniture",
    subcategory: null,
    name: "イルカの食器棚",
    nameI18n: {"ja":"イルカの食器棚","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/100.PNG",
    price: 1000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 115,
    category: "furniture",
    subcategory: null,
    name: "貝殻のコーナー吊戸棚",
    nameI18n: {"ja":"貝殻のコーナー吊戸棚","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/101.PNG",
    price: 750,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 116,
    category: "furniture",
    subcategory: null,
    name: "タツノオトシゴのコーナー吊戸棚",
    nameI18n: {"ja":"タツノオトシゴのコーナー吊戸棚","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/102.PNG",
    price: 750,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 117,
    category: "furniture",
    subcategory: null,
    name: "海の食器棚",
    nameI18n: {"ja":"海の食器棚","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/103.PNG",
    price: 1250,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 118,
    category: "furniture",
    subcategory: null,
    name: "貝殻のレンジフード",
    nameI18n: {"ja":"貝殻のレンジフード","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/104.PNG",
    price: 1000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 119,
    category: "furniture",
    subcategory: null,
    name: "カニのレンジフード",
    nameI18n: {"ja":"カニのレンジフード","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/105.PNG",
    price: 1000,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 120,
    category: "furniture",
    subcategory: null,
    name: "サンゴのトースター",
    nameI18n: {"ja":"サンゴのトースター","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/106.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 121,
    category: "furniture",
    subcategory: null,
    name: "舵輪のトースター",
    nameI18n: {"ja":"舵輪のトースター","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/107.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 122,
    category: "furniture",
    subcategory: null,
    name: "キッシンググラミーのトースター",
    nameI18n: {"ja":"キッシンググラミーのトースター","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/108.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 123,
    category: "furniture",
    subcategory: null,
    name: "海のコーヒーマシン",
    nameI18n: {"ja":"海のコーヒーマシン","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/109.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 124,
    category: "furniture",
    subcategory: null,
    name: "海の多ドア式冷蔵庫",
    nameI18n: {"ja":"海の多ドア式冷蔵庫","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/110.PNG",
    price: 1250,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 125,
    category: "furniture",
    subcategory: null,
    name: "海の多ドア式冷蔵庫",
    nameI18n: {"ja":"海の多ドア式冷蔵庫","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/111.PNG",
    price: 1250,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 126,
    category: "furniture",
    subcategory: null,
    name: "魚のフロアランプ",
    nameI18n: {"ja":"魚のフロアランプ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/112.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 127,
    category: "furniture",
    subcategory: null,
    name: "タコのフロアランプ",
    nameI18n: {"ja":"タコのフロアランプ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/113.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 128,
    category: "furniture",
    subcategory: null,
    name: "貝殻の食器",
    nameI18n: {"ja":"貝殻の食器","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/114.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 129,
    category: "furniture",
    subcategory: null,
    name: "貝殻の食器",
    nameI18n: {"ja":"貝殻の食器","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/115.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 130,
    category: "furniture",
    subcategory: null,
    name: "波のクジラ盆栽",
    nameI18n: {"ja":"波のクジラ盆栽","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/116.PNG",
    price: 600,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 131,
    category: "furniture",
    subcategory: null,
    name: "海の掛け絵",
    nameI18n: {"ja":"海の掛け絵","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/117.PNG",
    price: 1520,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 132,
    category: "furniture",
    subcategory: null,
    name: "クジラの掛け絵",
    nameI18n: {"ja":"クジラの掛け絵","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/118.PNG",
    price: 1520,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 133,
    category: "furniture",
    subcategory: null,
    name: "ウミガメの掛け絵",
    nameI18n: {"ja":"ウミガメの掛け絵","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/119.PNG",
    price: 1520,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 134,
    category: "furniture",
    subcategory: null,
    name: "幻想ホエールフォールパズル",
    nameI18n: {"ja":"幻想ホエールフォールパズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/120.PNG",
    price: 6400,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 135,
    category: "furniture",
    subcategory: null,
    name: "ホエールフォール峡谷パズル",
    nameI18n: {"ja":"ホエールフォール峡谷パズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/121.PNG",
    price: 6400,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 136,
    category: "furniture",
    subcategory: null,
    name: "仲良しイルカパズル",
    nameI18n: {"ja":"仲良しイルカパズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/122.PNG",
    price: 3760,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 137,
    category: "furniture",
    subcategory: null,
    name: "天然のギャラリーパズル",
    nameI18n: {"ja":"天然のギャラリーパズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/123.PNG",
    price: 3760,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 138,
    category: "furniture",
    subcategory: null,
    name: "海洋風景パズル",
    nameI18n: {"ja":"海洋風景パズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/124.PNG",
    price: 3760,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 139,
    category: "furniture",
    subcategory: null,
    name: "イルカのひとり旅パズル",
    nameI18n: {"ja":"イルカのひとり旅パズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/125.PNG",
    price: 3760,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 140,
    category: "furniture",
    subcategory: null,
    name: "カクレクマノミの群れパズル",
    nameI18n: {"ja":"カクレクマノミの群れパズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/126.PNG",
    price: 1200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 141,
    category: "furniture",
    subcategory: null,
    name: "ビーチタイムパズル",
    nameI18n: {"ja":"ビーチタイムパズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/127.PNG",
    price: 1200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 142,
    category: "furniture",
    subcategory: null,
    name: "森の夕暮れパズル",
    nameI18n: {"ja":"森の夕暮れパズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/128.PNG",
    price: 1200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 143,
    category: "furniture",
    subcategory: null,
    name: "ホエールデッキパズル",
    nameI18n: {"ja":"ホエールデッキパズル","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/129.PNG",
    price: 1200,
    currency: "トレンドコイン",
    limit: null,
    season: "whale_2026",
  },
  {
    id: 144,
    category: "other",
    subcategory: null,
    name: "ちびタコの虫取り網",
    nameI18n: {"ja":"ちびタコの虫取り網","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/130.PNG",
    price: 10000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 145,
    category: "other",
    subcategory: null,
    name: "海セダン",
    nameI18n: {"ja":"海セダン","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/131.PNG",
    price: 80000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 146,
    category: "other",
    subcategory: null,
    name: "海ミニバイク",
    nameI18n: {"ja":"海ミニバイク","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/132.PNG",
    price: 20000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 147,
    category: "other",
    subcategory: null,
    name: "海クロスバイク",
    nameI18n: {"ja":"海クロスバイク","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/133.PNG",
    price: 20000,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 148,
    category: "other",
    subcategory: null,
    name: "エモート「こっち見て」",
    nameI18n: {"ja":"エモート「こっち見て」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/134.jpg",
    price: 5400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 149,
    category: "other",
    subcategory: null,
    name: "エモート「つま先クイクイ」",
    nameI18n: {"ja":"エモート「つま先クイクイ」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/135.jpg",
    price: 5400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 150,
    category: "other",
    subcategory: null,
    name: "エモート「ハッピーダンス3」",
    nameI18n: {"ja":"エモート「ハッピーダンス3」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/136.jpg",
    price: 5400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 151,
    category: "other",
    subcategory: null,
    name: "エモート「ピュアアピール」",
    nameI18n: {"ja":"エモート「ピュアアピール」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/137.jpg",
    price: 5400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 152,
    category: "other",
    subcategory: null,
    name: "エモート「指ハート」",
    nameI18n: {"ja":"エモート「指ハート」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/138.jpg",
    price: 5400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 153,
    category: "other",
    subcategory: null,
    name: "エモート「かわいいダンス7」",
    nameI18n: {"ja":"エモート「かわいいダンス7」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/139.jpg",
    price: 5400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  {
    id: 154,
    category: "other",
    subcategory: null,
    name: "エモート「かわいいダンス8」",
    nameI18n: {"ja":"エモート「かわいいダンス8」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/whale/140.jpg",
    price: 5400,
    currency: "トレンドコイン",
    limit: 1,
    season: "whale_2026",
  },
  // 「原始の呼び声」フェス（primitive_2026）
  {
    id: 155,
    category: "other",
    subcategory: null,
    name: "エモート「考えるフリ」",
    nameI18n: {"ja":"エモート「考えるフリ」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/001.jpg",
    price: 8000,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 156,
    category: "other",
    subcategory: null,
    name: "エモート「異変察知」",
    nameI18n: {"ja":"エモート「異変察知」","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/002.jpg",
    price: 8000,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 157,
    category: "furniture",
    subcategory: null,
    name: "ドードー人形の置物",
    nameI18n: {"ja":"ドードー人形の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/003.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 158,
    category: "furniture",
    subcategory: null,
    name: "ドードー人形の置物",
    nameI18n: {"ja":"ドードー人形の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/004.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 159,
    category: "furniture",
    subcategory: null,
    name: "ドードー人形の置物",
    nameI18n: {"ja":"ドードー人形の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/005.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 160,
    category: "furniture",
    subcategory: null,
    name: "ドードー人形の置物",
    nameI18n: {"ja":"ドードー人形の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/006.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 161,
    category: "furniture",
    subcategory: null,
    name: "ドードー人形の置物",
    nameI18n: {"ja":"ドードー人形の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/007.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 162,
    category: "furniture",
    subcategory: null,
    name: "ドードー人形の置物",
    nameI18n: {"ja":"ドードー人形の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/008.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 163,
    category: "furniture",
    subcategory: null,
    name: "獣骨模型の置物",
    nameI18n: {"ja":"獣骨模型の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/009.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 164,
    category: "furniture",
    subcategory: null,
    name: "獣骨模型の置物",
    nameI18n: {"ja":"獣骨模型の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/010.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 165,
    category: "furniture",
    subcategory: null,
    name: "獣骨模型の置物",
    nameI18n: {"ja":"獣骨模型の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/011.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 166,
    category: "furniture",
    subcategory: null,
    name: "獣骨模型の置物",
    nameI18n: {"ja":"獣骨模型の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/012.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 167,
    category: "furniture",
    subcategory: null,
    name: "獣骨模型の置物",
    nameI18n: {"ja":"獣骨模型の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/013.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 168,
    category: "furniture",
    subcategory: null,
    name: "獣骨模型の置物",
    nameI18n: {"ja":"獣骨模型の置物","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/014.PNG",
    price: 1600,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 169,
    category: "fashion",
    subcategory: "setup",
    name: "プリミティブセットアップ",
    nameI18n: {"ja":"プリミティブセットアップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/015.PNG",
    price: 5200,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 170,
    category: "fashion",
    subcategory: "setup",
    name: "プリミティブセットアップ",
    nameI18n: {"ja":"プリミティブセットアップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/016.PNG",
    price: 5200,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 171,
    category: "fashion",
    subcategory: "setup",
    name: "プリミティブセットアップ",
    nameI18n: {"ja":"プリミティブセットアップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/017.PNG",
    price: 5200,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 172,
    category: "fashion",
    subcategory: "setup",
    name: "プリミティブセットアップ",
    nameI18n: {"ja":"プリミティブセットアップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/018.PNG",
    price: 5200,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 173,
    category: "fashion",
    subcategory: "setup",
    name: "プリミティブセットアップ",
    nameI18n: {"ja":"プリミティブセットアップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/019.PNG",
    price: 5200,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 174,
    category: "fashion",
    subcategory: "setup",
    name: "プリミティブセットアップ",
    nameI18n: {"ja":"プリミティブセットアップ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/020.PNG",
    price: 5200,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 175,
    category: "furniture",
    subcategory: null,
    name: "子牛のペットソファ",
    nameI18n: {"ja":"子牛のペットソファ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/021.PNG",
    price: 1800,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 176,
    category: "furniture",
    subcategory: null,
    name: "子牛のペットソファ",
    nameI18n: {"ja":"子牛のペットソファ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/022.PNG",
    price: 1800,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 177,
    category: "furniture",
    subcategory: null,
    name: "子牛のペットソファ",
    nameI18n: {"ja":"子牛のペットソファ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/023.PNG",
    price: 1800,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 178,
    category: "furniture",
    subcategory: null,
    name: "子牛のペットソファ",
    nameI18n: {"ja":"子牛のペットソファ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/024.PNG",
    price: 1800,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 179,
    category: "furniture",
    subcategory: null,
    name: "子牛のペットソファ",
    nameI18n: {"ja":"子牛のペットソファ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/025.PNG",
    price: 1800,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 180,
    category: "furniture",
    subcategory: null,
    name: "子牛のペットソファ",
    nameI18n: {"ja":"子牛のペットソファ","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/026.PNG",
    price: 1800,
    currency: "フェスコイン",
    limit: null,
    season: "primitive_2026",
  },
  {
    id: 181,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(左パーツ)",
    nameI18n: {"ja":"カピバラの石版(左パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/027.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 182,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(左パーツ)",
    nameI18n: {"ja":"カピバラの石版(左パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/028.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 183,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(左パーツ)",
    nameI18n: {"ja":"カピバラの石版(左パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/029.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 184,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(中央パーツ)",
    nameI18n: {"ja":"カピバラの石版(中央パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/030.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 185,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(中央パーツ)",
    nameI18n: {"ja":"カピバラの石版(中央パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/031.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 186,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(中央パーツ)",
    nameI18n: {"ja":"カピバラの石版(中央パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/032.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 187,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(右パーツ)",
    nameI18n: {"ja":"カピバラの石版(右パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/033.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 188,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(右パーツ)",
    nameI18n: {"ja":"カピバラの石版(右パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/034.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 189,
    category: "furniture",
    subcategory: null,
    name: "カピバラの石版(右パーツ)",
    nameI18n: {"ja":"カピバラの石版(右パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/035.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 190,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(上パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(上パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/036.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 191,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(上パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(上パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/037.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 192,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(上パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(上パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/038.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 193,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(中央パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(中央パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/039.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 194,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(中央パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(中央パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/040.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 195,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(中央パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(中央パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/041.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 196,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(下パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(下パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/042.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 197,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(下パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(下パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/043.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
  {
    id: 198,
    category: "furniture",
    subcategory: null,
    name: "ウォーキーの石版(下パーツ)",
    nameI18n: {"ja":"ウォーキーの石版(下パーツ)","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    img: "./images/genshi/044.PNG",
    price: 2600,
    currency: "フェスコイン",
    limit: 1,
    season: "primitive_2026",
  },
];

// シーズン情報（複数シーズンが増えても、ここに追記していく想定）
const shopSeasons = {
  whale_2026: {
    label: "ホエールシーズン",
    labelI18n: {"ja":"ホエールシーズン","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    start: "2026-07-11 06:00",
    end: "2026-08-22 05:59",
  },
  // 「原始の呼び声」フェス（2026-08-29開始）
  primitive_2026: {
    label: "原始の呼び声",
    labelI18n: {"ja":"原始の呼び声","en":"","zh-CN":"","zh-TW":"","ko":"","th":""},
    start: "2026-08-29 06:00",
    end: "2026-10-09 05:59",
  },
};
