const dogFoods = [
{name:{jp:"動物汎用エサ",en:"Generic Feed",zh_cn:"通用饲料",zh_tw:"通用飼料",ko:"범용 사료",th:"อาหารทั่วไป",tl:"Pangkalahatang pagkain"},img:"./images/petfoods/001.PNG"},
{name:{jp:"ドッグフード",en:"Dog Food",zh_cn:"狗粮",zh_tw:"狗糧",ko:"강아지 사료",th:"อาหารสุนัข",tl:"Pagkain ng aso"},img:"./images/petfoods/002.PNG"},
{name:{jp:"ヒラタケ",en:"Oyster Mushroom",zh_cn:"平菇",zh_tw:"平菇",ko:"느타리버섯",th:"เห็ดนางรม",tl:"Oyster mushroom"},img:"./images/petfoods/003.PNG"},
{name:{jp:"シイタケ",en:"Shiitake",zh_cn:"香菇",zh_tw:"香菇",ko:"표고버섯",th:"เห็ดชิตาเกะ",tl:"Shiitake"},img:"./images/petfoods/004.PNG"},
{name:{jp:"マッシュルーム",en:"Mushroom",zh_cn:"蘑菇",zh_tw:"蘑菇",ko:"양송이버섯",th:"เห็ด",tl:"Kabute"},img:"./images/petfoods/005.PNG"},
{name:{jp:"リンゴ",en:"Apple",zh_cn:"苹果",zh_tw:"蘋果",ko:"사과",th:"แอปเปิล",tl:"Mansanas"},img:"./images/petfoods/006.PNG"},
{name:{jp:"田園サラダ",en:"Country Salad",zh_cn:"田园沙拉",zh_tw:"田園沙拉",ko:"컨트리 샐러드",th:"สลัดชนบท",tl:"Country salad"},img:"./images/petfoods/007.PNG"},
{name:{jp:"ミックスジャム",en:"Mixed Jam",zh_cn:"混合果酱",zh_tw:"混合果醬",ko:"믹스 잼",th:"แยมรวม",tl:"Mixed jam"},img:"./images/petfoods/008.PNG"},
{name:{jp:"ラズベリージャム",en:"Raspberry Jam",zh_cn:"覆盆子果酱",zh_tw:"覆盆子果醬",ko:"라즈베리 잼",th:"แยมราสเบอร์รี่",tl:"Raspberry jam"},img:"./images/petfoods/009.PNG"},
{name:{jp:"トマトソース",en:"Tomato Sauce",zh_cn:"番茄酱",zh_tw:"番茄醬",ko:"토마토 소스",th:"ซอสมะเขือเทศ",tl:"Tomato sauce"},img:"./images/petfoods/010.PNG"},
{name:{jp:"ブルーベリージャム",en:"Blueberry Jam",zh_cn:"蓝莓果酱",zh_tw:"藍莓果醬",ko:"블루베리 잼",th:"แยมบลูเบอร์รี่",tl:"Blueberry jam"},img:"./images/petfoods/011.PNG"},
{name:{jp:"リンゴジャム",en:"Apple Jam",zh_cn:"苹果果酱",zh_tw:"蘋果果醬",ko:"사과 잼",th:"แยมแอปเปิล",tl:"Apple jam"},img:"./images/petfoods/012.PNG"},
{name:{jp:"イチゴジャム",en:"Strawberry Jam",zh_cn:"草莓果酱",zh_tw:"草莓果醬",ko:"딸기 잼",th:"แยมสตรอว์เบอร์รี่",tl:"Strawberry jam"},img:"./images/petfoods/013.PNG"},
{name:{jp:"キノコパイ",en:"Mushroom Pie",zh_cn:"蘑菇派",zh_tw:"蘑菇派",ko:"버섯 파이",th:"พายเห็ด",tl:"Mushroom pie"},img:"./images/petfoods/014.PNG"},
{name:{jp:"マッシュルームパイ",en:"Mushroom Pie",zh_cn:"蘑菇派",zh_tw:"蘑菇派",ko:"버섯 파이",th:"พายเห็ด",tl:"Mushroom pie"},img:"./images/petfoods/017.PNG"},
{name:{jp:"シイタケパイ",en:"Shiitake Pie",zh_cn:"香菇派",zh_tw:"香菇派",ko:"표고 파이",th:"พายเห็ดชิตาเกะ",tl:"Shiitake pie"},img:"./images/petfoods/016.PNG"},
{name:{jp:"ヒラタケパイ",en:"Oyster Mushroom Pie",zh_cn:"平菇派",zh_tw:"平菇派",ko:"느타리 파이",th:"พายเห็ดนางรม",tl:"Oyster mushroom pie"},img:"./images/petfoods/015.PNG"},
{name:{jp:"焼きキノコ",en:"Grilled Mushrooms",zh_cn:"烤蘑菇",zh_tw:"烤蘑菇",ko:"구운 버섯",th:"เห็ดย่าง",tl:"Inihaw na kabute"},img:"./images/petfoods/018.PNG"},
{name:{jp:"焼きヒラタケ",en:"Grilled Oyster Mushroom",zh_cn:"烤平菇",zh_tw:"烤平菇",ko:"구운 느타리",th:"เห็ดนางรมย่าง",tl:"Inihaw na oyster mushroom"},img:"./images/petfoods/019.PNG"},
{name:{jp:"焼きシイタケ",en:"Grilled Shiitake",zh_cn:"烤香菇",zh_tw:"烤香菇",ko:"구운 표고",th:"เห็ดชิตาเกะย่าง",tl:"Inihaw na shiitake"},img:"./images/petfoods/020.PNG"},
{name:{jp:"焼きマッシュルーム",en:"Grilled Mushroom",zh_cn:"烤蘑菇",zh_tw:"烤蘑菇",ko:"구운 양송이",th:"เห็ดย่าง",tl:"Inihaw na kabute"},img:"./images/petfoods/021.PNG"},
{name:{jp:"シーフードリゾート",en:"Seafood Risotto",zh_cn:"海鲜烩饭",zh_tw:"海鮮燉飯",ko:"해산물 리조또",th:"รีซอตโตทะเล",tl:"Seafood risotto"},img:"./images/petfoods/022.PNG"},
{name:{jp:"カントリー風煮込み",en:"Country Stew",zh_cn:"乡村炖菜",zh_tw:"鄉村燉菜",ko:"컨트리 스튜",th:"สตูว์ชนบท",tl:"Country stew"},img:"./images/petfoods/023.PNG"},
{name:{jp:"ミートソースパスタ",en:"Meat Sauce Pasta",zh_cn:"肉酱意面",zh_tw:"肉醬義大利麵",ko:"미트소스 파스타",th:"พาสต้าเนื้อ",tl:"Pasta na may meat sauce"},img:"./images/petfoods/024.PNG"},
{name:{jp:"コーンポタージュ",en:"Corn Soup",zh_cn:"玉米浓汤",zh_tw:"玉米濃湯",ko:"옥수수 스프",th:"ซุปข้าวโพด",tl:"Corn soup"},img:"./images/petfoods/025.PNG"},
{name:{jp:"豪華海鮮盛り合わせ",en:"Seafood Platter",zh_cn:"豪华海鲜拼盘",zh_tw:"豪華海鮮拼盤",ko:"해산물 모둠",th:"ซีฟู้ดรวม",tl:"Seafood platter"},img:"./images/petfoods/026.PNG"},
{name:{jp:"ミートバーガー",en:"Meat Burger",zh_cn:"肉汉堡",zh_tw:"肉漢堡",ko:"고기 버거",th:"เบอร์เกอร์เนื้อ",tl:"Meat burger"},img:"./images/petfoods/027.PNG"},
{name:{jp:"ナスとひき肉の炒め物",en:"Eggplant & Minced Meat",zh_cn:"茄子炒肉末",zh_tw:"茄子炒肉末",ko:"가지 다진고기 볶음",th:"ผัดมะเขือกับหมูสับ",tl:"Ginisang talong"},img:"./images/petfoods/028.PNG"},
{name:{jp:"蒸しタラバガニ",en:"Steamed King Crab",zh_cn:"清蒸帝王蟹",zh_tw:"清蒸帝王蟹",ko:"찐 킹크랩",th:"ปูคิงแครบ",tl:"Steamed king crab"},img:"./images/petfoods/029.PNG"},
{name:{jp:"蒸し黄金タラバガニ",en:"Golden King Crab",zh_cn:"黄金帝王蟹",zh_tw:"黃金帝王蟹",ko:"황금 킹크랩",th:"ปูทอง",tl:"Golden king crab"},img:"./images/petfoods/030.PNG"},
{name:{jp:"大根おろし肉",en:"Grated Radish Meat",zh_cn:"萝卜泥肉",zh_tw:"蘿蔔泥肉",ko:"무 고기 요리",th:"เนื้อกับหัวไชเท้า",tl:"Karne na may labanos"},img:"./images/petfoods/031.PNG"},
{name:{jp:"大根クリームポタージュ",en:"Radish Cream Soup",zh_cn:"萝卜奶油汤",zh_tw:"蘿蔔奶油湯",ko:"무 크림 스프",th:"ซุปหัวไชเท้า",tl:"Radish cream soup"},img:"./images/petfoods/032.PNG"}
];
