// 虫
const bugData = [
{
 name:"キアゲハ",
 nameI18n:{"ja":"キアゲハ","en":"Old World Swallowtail","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:30,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林",
 locationI18n:{"ja":"森林","en":"Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/001.PNG"
},
{
 name:"クモマツマキチョウ",
 nameI18n:{"ja":"クモマツマキチョウ","en":"Orange Tip","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:30,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"中心街",
 locationI18n:{"ja":"中心街","en":"Downtown","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/002.PNG"
},
{
 name:"ヤマキチョウ",
 nameI18n:{"ja":"ヤマキチョウ","en":"Brimstone Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:30,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/003.PNG"
},
{
 name:"モンシロチョウ",
 nameI18n:{"ja":"モンシロチョウ","en":"Cabbage White","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:30,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村",
 locationI18n:{"ja":"漁村","en":"Fishing Village","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/004.PNG"
},
{
 name:"アポロウスバシロチョウ",
 nameI18n:{"ja":"アポロウスバシロチョウ","en":"Apollo Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:30,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"虫コイコイクエスト",
 locationI18n:{"ja":"虫コイコイクエスト","en":"Bug Luring Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/005.PNG"
},
{
 name:"ベニモンアゲハ",
 nameI18n:{"ja":"ベニモンアゲハ","en":"Crimson Rose Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:30,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"虫コイコイクエスト",
 locationI18n:{"ja":"虫コイコイクエスト","en":"Bug Luring Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/006.PNG"
},
{
 name:"スルコウスキーモルフォ",
 nameI18n:{"ja":"スルコウスキーモルフォ","en":"Sulkowsky's Morpho","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:90,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"エアーミツバチ虫寄せ装置",
 locationI18n:{"ja":"エアーミツバチ虫寄せ装置","en":"Air Bee Bug Attractor","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/007.PNG"
},
{
 name:"アスバラカズハムシ",
 nameI18n:{"ja":"アスバラカズハムシ","en":"Asparagus Beetle","zh-CN":"","zh-TW":"","ko":"","th":""}, 
 level:1,
 price:55,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑",
 locationI18n:{"ja":"花畑","en":"Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/008.PNG"
},
{
 name:"クリソクラオン",
 nameI18n:{"ja":"クリソクラオン","en":"Chrysochroa Jewel Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:45,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山",
 locationI18n:{"ja":"温泉山","en":"Hot Spring Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/009.PNG"
},
{
 name:"コバネアカホシカメムシ",
 nameI18n:{"ja":"コバネアカホシカメムシ","en":"Red-spotted Stink Bug","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:35,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"ホーム",
 locationI18n:{"ja":"ホーム","en":"Home","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/010.PNG"
},
{
 name:"アカイトトンボ",
 nameI18n:{"ja":"アカイトトンボ","en":"Small Red Damselfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:35,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"水辺",
 locationI18n:{"ja":"水辺","en":"Waterside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/011.PNG"
},
{
 name:"イカルスヒメシジミ",
 nameI18n:{"ja":"イカルスヒメシジミ","en":"Common Blue Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:105,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"中心街",
 locationI18n:{"ja":"中心街","en":"Downtown","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/012.PNG"
},
{
 name:"ミドリニワハンミョウ",
 nameI18n:{"ja":"ミドリニワハンミョウ","en":"Green Tiger Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:110,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山",
 locationI18n:{"ja":"温泉山","en":"Hot Spring Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/013.PNG"
},
{
 name:"コウホウトラカミキリ",
 nameI18n:{"ja":"コウホウトラカミキリ","en":"Tiger Longhorn Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:110,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林",
 locationI18n:{"ja":"森林","en":"Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/014.PNG"
},
{
 name:"アオホシハナムグリ",
 nameI18n:{"ja":"アオホシハナムグリ","en":"Blue-spotted Flower Chafer","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:165,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"ホーム",
 locationI18n:{"ja":"ホーム","en":"Home","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/015.PNG"
},
{
 name:"シベリアヒナバッタ",
 nameI18n:{"ja":"シベリアヒナバッタ","en":"Siberian Grasshopper","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:90,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村",
 locationI18n:{"ja":"漁村","en":"Fishing Village","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/016.PNG"
},
{
 name:"ナナホシテントウ",
 nameI18n:{"ja":"ナナホシテントウ","en":"Seven-spot Ladybird","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:110,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/017.PNG"
},
{
 name:"ヨツボシトンボ",
 nameI18n:{"ja":"ヨツボシトンボ","en":"Four-spotted Chaser","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:75,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖畔",
 locationI18n:{"ja":"郊外の湖畔","en":"Suburban Lakeside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/018.PNG"
},
{
 name:"クマバチ",
 nameI18n:{"ja":"クマバチ","en":"Carpenter Bee","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:110,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑",
 locationI18n:{"ja":"花畑","en":"Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/019.PNG"
},
{
 name:"イリスコムラサキ",
 nameI18n:{"ja":"イリスコムラサキ","en":"Purple Emperor","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:90,
 weather:["晴れ","虹"],
 time:["12-18","18-0","0-6"],
 location:"花畑-クジラ山",
 locationI18n:{"ja":"花畑-クジラ山","en":"Flower Field - Whale Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/020.PNG"
},
{
 name:"アカエリトリバネアゲハ",
 nameI18n:{"ja":"アカエリトリバネアゲハ","en":"Red-collared Birdwing","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:90,
 weather:["晴れ","雨","虹"],
 time:["6-12","18-0","0-6"],
 location:"ホーム",
 locationI18n:{"ja":"ホーム","en":"Home","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/021.PNG"
},
{
 name:"ヒメオナガミズアオ",
 nameI18n:{"ja":"ヒメオナガミズアオ","en":"Small Luna Moth","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:105,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/022.PNG"
},
{
 name:"アカハネムシ",
 nameI18n:{"ja":"アカハネムシ","en":"Red Net-winged Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:110,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-温泉",
 locationI18n:{"ja":"温泉山-温泉","en":"Hot Spring Mountain - Hot Spring","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/024.PNG"
},
{
 name:"ピンクタイワンクツワムシ",
 nameI18n:{"ja":"ピンクタイワンクツワムシ","en":"Pink Taiwan Katydid","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:90,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"虫コイコイクエスト",
 locationI18n:{"ja":"虫コイコイクエスト","en":"Bug Luring Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/023.PNG"
},
{
 name:"キリギリス",
 nameI18n:{"ja":"キリギリス","en":"Bush Cricket","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:180,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-パープルビーチ",
 locationI18n:{"ja":"花畑-パープルビーチ","en":"Flower Field - Purple Beach","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/025.PNG"
},
{
 name:"シロマダラオバチ",
 nameI18n:{"ja":"シロマダラオバチ","en":"White-spotted Giant Wasp","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:165,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0"],
 location:"森林-コジカ塔",
 locationI18n:{"ja":"森林-コジカ塔","en":"Forest - Fawn Tower","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/026.PNG"
},
{
 name:"アリ",
 nameI18n:{"ja":"アリ","en":"Ant","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:220,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村-漁村広場",
 locationI18n:{"ja":"漁村-漁村広場","en":"Fishing Village - Village Square","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/027.PNG"
},
{
 name:"ツマグロヒョウモン",
 nameI18n:{"ja":"ツマグロヒョウモン","en":"Indian Fritillary","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:90,
 weather:["雨","虹"],
 time:["6-12","18-0","0-6"],
 location:"漁村-波止場",
 locationI18n:{"ja":"漁村-波止場","en":"Fishing Village - Pier","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/028.PNG"
},
{
 name:"アルキプテラフスカ",
 nameI18n:{"ja":"アルキプテラフスカ","en":"Arcyptera Grasshopper","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:140,
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/029.PNG"
},
{
 name:"ヨツボシテントウ",
 nameI18n:{"ja":"ヨツボシテントウ","en":"Four-spotted Ladybird","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:165,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-火山湖",
 locationI18n:{"ja":"温泉山-火山湖","en":"Hot Spring Mountain - Volcanic Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/030.PNG"
},
{
 name:"セミ",
 nameI18n:{"ja":"セミ","en":"Cicada","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:220,
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0","0-6"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/031.PNG"
},
{
 name:"シオカラトンボ",
 nameI18n:{"ja":"シオカラトンボ","en":"White-tailed Skimmer","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:75,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"川辺",
 locationI18n:{"ja":"川辺","en":"Riverside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/032.PNG"
},
{
 name:"ニジイロカマキリ",
 nameI18n:{"ja":"ニジイロカマキリ","en":"Rainbow Mantis","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:195,
 weather:["晴れ","虹"],
 time:["12-18","18-0","0-6"],
 location:"温泉山-石海岸の崖",
 locationI18n:{"ja":"温泉山-石海岸の崖","en":"Hot Spring Mountain - Rocky Coast Cliff","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/033.PNG"
},
{
 name:"クジャクチョウ",
 nameI18n:{"ja":"クジャクチョウ","en":"Peacock Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:90,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-風車の花畑",
 locationI18n:{"ja":"花畑-風車の花畑","en":"Flower Field - Windmill Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/034.PNG"
},
{
 name:"キベリタテハ",
 nameI18n:{"ja":"キベリタテハ","en":"Camberwell Beauty","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:90,
 weather:["晴れ","虹"],
 time:["6-12","12-18","0-6"],
 location:"温泉山-温泉",
 locationI18n:{"ja":"温泉山-温泉","en":"Hot Spring Mountain - Hot Spring","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/035.PNG"
},
{
 name:"ナンベイオオヤガ",
 nameI18n:{"ja":"ナンベイオオヤガ","en":"South American Owlet Moth","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:90,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"虫コイコイクエスト",
 locationI18n:{"ja":"虫コイコイクエスト","en":"Bug Luring Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/036.PNG"
},
{
 name:"タケウチトゲムネカミキリ",
 nameI18n:{"ja":"タケウチトゲムネカミキリ","en":"Takeuchi's Spiny Longhorn Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:165,
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-森の島",
 locationI18n:{"ja":"森林-森の島","en":"Forest - Forest Island","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/037.PNG"
},
{
 name:"ナミテントウ",
 nameI18n:{"ja":"ナミテントウ","en":"Asian Lady Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:165,
 weather:["雨","虹"],
 time:["12-18","18-0","0-6"],
 location:"森林-コジカ塔",
 locationI18n:{"ja":"森林-コジカ塔","en":"Forest - Fawn Tower","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/038.PNG"
},
{
 name:"パプアハラビロカマキリ",
 nameI18n:{"ja":"パプアハラビロカマキリ","en":"Papua Broad-winged Mantis","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:390,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-遺跡",
 locationI18n:{"ja":"温泉山-遺跡","en":"Hot Spring Mountain - Ruins","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/039.PNG"
},
{
 name:"ムラサキクマバチ",
 nameI18n:{"ja":"ムラサキクマバチ","en":"Violet Carpenter Bee","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:165,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-クジラ山",
 locationI18n:{"ja":"花畑-クジラ山","en":"Flower Field - Whale Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/040.PNG"
},
{
 name:"オオミドリトリバネアゲハ",
 nameI18n:{"ja":"オオミドリトリバネアゲハ","en":"Green Birdwing","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:150,
 weather:["晴れ","雨","虹"],
 time:["18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/041.PNG"
},
{
 name:"ミヤマクワガタ",
 nameI18n:{"ja":"ミヤマクワガタ","en":"Miyama Stag Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:275,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0"],
 location:"森林-ジャンプステージ",
 locationI18n:{"ja":"森林-ジャンプステージ","en":"Forest - Jump Stage","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/042.PNG"
},
{
 name:"シルバージュエルコガネ",
 nameI18n:{"ja":"シルバージュエルコガネ","en":"Silver Jewel Scarab","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:165,
 weather:["晴れ","虹"],
 time:["6-12","12-18","0-6"],
 location:"温泉山-石海岸の崖",
 locationI18n:{"ja":"温泉山-石海岸の崖","en":"Hot Spring Mountain - Rocky Coast Cliff","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/043.PNG"
},
{
 name:"ルリクチブトカメムシ",
 nameI18n:{"ja":"ルリクチブトカメムシ","en":"Blue Shield Bug","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:110,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18"],
 location:"漁村-灯台",
 locationI18n:{"ja":"漁村-灯台","en":"Fishing Village - Lighthouse","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/044.PNG"
},
{
 name:"アオハダトンボ",
 nameI18n:{"ja":"アオハダトンボ","en":"Blue-winged Demoiselle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:110,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森の湖畔",
 locationI18n:{"ja":"森の湖畔","en":"Forest Lakeside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/045.PNG"
},
{
 name:"メネラウスモルフォ",
 nameI18n:{"ja":"メネラウスモルフォ","en":"Menelaus Blue Morpho","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:150,
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/046.PNG"
},
{
 name:"アサギマダラ",
 nameI18n:{"ja":"アサギマダラ","en":"Chestnut Tiger Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:150,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"虫コイコイクエスト",
 locationI18n:{"ja":"虫コイコイクエスト","en":"Bug Luring Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/047.PNG"
},
{
 name:"ミノタウロスコガネ",
 nameI18n:{"ja":"ミノタウロスコガネ","en":"Minotaur Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:275,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","0-6"],
 location:"温泉山-遺跡",
 locationI18n:{"ja":"温泉山-遺跡","en":"Hot Spring Mountain - Ruins","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/048.PNG"
},
{
 name:"ビューティースペキオーサ",
 nameI18n:{"ja":"ビューティースペキオーサ","en":"Speciosa Jewel Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:275,
 weather:["雨","虹"],
 time:["6-12","12-18"],
 location:"花畑-クジラ山",
 locationI18n:{"ja":"花畑-クジラ山","en":"Flower Field - Whale Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/049.PNG"
},
{
 name:"ゴールドジュエルコガネ",
 nameI18n:{"ja":"ゴールドジュエルコガネ","en":"Gold Jewel Scarab","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:275,
 weather:["晴れ","虹"],
 time:["12-18","18-0"],
 location:"森林-ジャンプステージ",
 locationI18n:{"ja":"森林-ジャンプステージ","en":"Forest - Jump Stage","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/050.PNG"
},
{
 name:"ロサトンボ",
 nameI18n:{"ja":"ロサトンボ","en":"Rosa Dragonfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:185,
 weather:["虹"],
 time:["12-18","18-0","0-6"],
 location:"温泉山の湖畔",
 locationI18n:{"ja":"温泉山の湖畔","en":"Hot Spring Mountain Lakeside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/051.PNG"
},
{
 name:"イザベラミズアオ",
 nameI18n:{"ja":"イザベラミズアオ","en":"Isabella Moon Moth","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:150,
 weather:["晴れ","虹"],
 time:["12-18","18-0"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/052.PNG"
},
{
 name:"マダガスカルムーンモス",
 nameI18n:{"ja":"マダガスカルムーンモス","en":"Madagascan Moon Moth","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:240,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/053.PNG"
},
{
 name:"カブトムシ",
 nameI18n:{"ja":"カブトムシ","en":"Japanese Rhinoceros Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:275,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"漁村-漁村東桟橋",
 locationI18n:{"ja":"漁村-漁村東桟橋","en":"Fishing Village - East Pier","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/054.PNG"
},
{
 name:"ピカソバグ",
 nameI18n:{"ja":"ピカソバグ","en":"Picasso Bug","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:185,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"花畑-パープルビーチ",
 locationI18n:{"ja":"花畑-パープルビーチ","en":"Flower Field - Purple Beach","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/055.PNG"
},
{
 name:"シンジュタテハ",
 nameI18n:{"ja":"シンジュタテハ","en":"Pearl Nymph Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:240,
 weather:["雨","虹"],
 time:["6-12","0-6"],
 location:"花畑-風車の花畑",
 locationI18n:{"ja":"花畑-風車の花畑","en":"Flower Field - Windmill Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/056.PNG"
},
{
 name:"オウゴンオニクワガタ",
 nameI18n:{"ja":"オウゴンオニクワガタ","en":"Golden Ogre Stag Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:440,
 weather:["雨","虹"],
 time:["18-0","0-6"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/057.PNG"
},
{
 name:"ニジイロクワガタ",
 nameI18n:{"ja":"ニジイロクワガタ","en":"Rainbow Stag Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:440,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"虫コイコイクエスト-遺跡(追加段階)",
 locationI18n:{"ja":"虫コイコイクエスト-遺跡(追加段階)","en":"Bug Luring Quest - Ruins (Extra Stage)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/058.PNG"
},
{
 name:"ヨウカイカマキリ",
 nameI18n:{"ja":"ヨウカイカマキリ","en":"Ghost Mantis","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:515,
 weather:["雨","虹"],
 time:["12-18","18-0"],
 location:"温泉山-遺跡",
 locationI18n:{"ja":"温泉山-遺跡","en":"Hot Spring Mountain - Ruins","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/059.PNG"
},
{
 name:"青いクマバチ",
 nameI18n:{"ja":"青いクマバチ","en":"Blue Carpenter Bee","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:440,
 weather:["虹"],
 time:["18-0","0-6"],
 location:"漁村-漁村広場",
 locationI18n:{"ja":"漁村-漁村広場","en":"Fishing Village - Village Square","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/060.PNG"
},
{
 name:"ヘレナモルフォ",
 nameI18n:{"ja":"ヘレナモルフォ","en":"Helena Morpho","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:240,
 weather:["虹"],
 time:["6-12","12-18"],
 location:"花畑-パープルビーチ",
 locationI18n:{"ja":"花畑-パープルビーチ","en":"Flower Field - Purple Beach","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/061.PNG"
},
{
 name:"タイヨウモルフォ",
 nameI18n:{"ja":"タイヨウモルフォ","en":"Sun Morpho","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:240,
 weather:["虹"],
 time:["6-12","12-18"],
 location:"森林-コジカ塔",
 locationI18n:{"ja":"森林-コジカ塔","en":"Forest - Fawn Tower","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/062.PNG"
},
{
 name:"ヘラクレスオオカブト",
 nameI18n:{"ja":"ヘラクレスオオカブト","en":"Hercules Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:440,
 weather:["晴れ","虹"],
 time:["12-18","18-0"],
 location:"温泉山-火山湖",
 locationI18n:{"ja":"温泉山-火山湖","en":"Hot Spring Mountain - Volcanic Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/063.PNG"
},
{
 name:"クロツヤミノガ",
 nameI18n:{"ja":"クロツヤミノガ","en":"Black Bagworm Moth","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:440,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"森林-コジカ塔",
 locationI18n:{"ja":"森林-コジカ塔","en":"Forest - Fawn Tower","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/064.PNG"
},
{
 name:"アレクサンドラトリバネアゲハ",
 nameI18n:{"ja":"アレクサンドラトリバネアゲハ","en":"Queen Alexandra's Birdwing","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 weather:["晴れ","虹"],
 time:["18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"アトラスオオカブト",
 nameI18n:{"ja":"アトラスオオカブト","en":"Atlas Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 weather:["虹"],
 time:["18-0","0-6"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"ジュウサンホシテントウ",
 nameI18n:{"ja":"ジュウサンホシテントウ","en":"Thirteen-spot Ladybird","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 weather:["虹"],
 time:["12-18","18-0"],
 location:"花畑-クジラ山",
 locationI18n:{"ja":"花畑-クジラ山","en":"Flower Field - Whale Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"ハナカマキリ",
 nameI18n:{"ja":"ハナカマキリ","en":"Orchid Mantis","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 weather:["雨","虹"],
 time:["6-12","12-18"],
 location:"温泉山-遺跡",
 locationI18n:{"ja":"温泉山-遺跡","en":"Hot Spring Mountain - Ruins","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"ミイロタイマイ",
 nameI18n:{"ja":"ミイロタイマイ","en":"Tricolor Swallowtail","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 weather:["雨","虹"],
 time:["6-12","18-0"],
 location:"花畑-風車の花畑",
 locationI18n:{"ja":"花畑-風車の花畑","en":"Flower Field - Windmill Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"オオサマゴライアス",
 nameI18n:{"ja":"オオサマゴライアス","en":"Goliath Beetle","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 weather:["虹"],
 time:["18-0","0-6"],
 location:"森林-コジカ塔",
 locationI18n:{"ja":"森林-コジカ塔","en":"Forest - Fawn Tower","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"トウワタバッタ",
 nameI18n:{"ja":"トウワタバッタ","en":"Milkweed Grasshopper","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 weather:["雨","虹"],
 time:["6-12","12-18"],
 location:"温泉山-温泉",
 locationI18n:{"ja":"温泉山-温泉","en":"Hot Spring Mountain - Hot Spring","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ベニトンボ",
 nameI18n:{"ja":"ベニトンボ","en":"Crimson Darter","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 weather:["虹"],
 time:["6-12","12-18"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"デイダミアモルフォ",
 nameI18n:{"ja":"デイダミアモルフォ","en":"Deidamia Morpho","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:13,
 weather:["虹"],
 time:["12-18","18-0"],
 location:"温泉山-火山湖",
 locationI18n:{"ja":"温泉山-火山湖","en":"Hot Spring Mountain - Volcanic Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ミドリカワトンボ",
 nameI18n:{"ja":"ミドリカワトンボ","en":"Green River Damselfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:13,
 weather:["雨","虹"],
 time:["12-18","18-0"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"グラスウィングバタフライ",
 nameI18n:{"ja":"グラスウィングバタフライ","en":"Glasswing Butterfly","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:14,
 weather:["雨","虹"],
 time:["12-18","18-0"],
 location:"花畑-クジラ山",
 locationI18n:{"ja":"花畑-クジラ山","en":"Flower Field - Whale Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"アオミオカタニシ",
 nameI18n:{"ja":"アオミオカタニシ","en":"Blue Land Snail","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:14,
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-森の島",
 locationI18n:{"ja":"森林-森の島","en":"Forest - Forest Island","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"積み木アカイトトンボ(ピンク)",
 nameI18n:{"ja":"積み木アカイトトンボ(ピンク)","en":"Building Block Small Red Damselfly (Pink)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-ジャンプステージ",
 locationI18n:{"ja":"森林-ジャンプステージ","en":"Forest - Jump Stage","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/1001.PNG",
 auth:false
},
{
 name:"積み木アカイトトンボ(黄)",
 nameI18n:{"ja":"積み木アカイトトンボ(黄)","en":"Building Block Small Red Damselfly (Yellow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/1002.PNG",
 auth:false
},
{
 name:"積み木アカイトトンボ(青)",
 nameI18n:{"ja":"積み木アカイトトンボ(青)","en":"Building Block Small Red Damselfly (Blue)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-コジカ塔",
 locationI18n:{"ja":"森林-コジカ塔","en":"Forest - Fawn Tower","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/1003.PNG",
 auth:false
},
{
 name:"積み木アカイトトンボ(紫)",
 nameI18n:{"ja":"積み木アカイトトンボ(紫)","en":"Building Block Small Red Damselfly (Purple)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:75,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-森の島",
 locationI18n:{"ja":"森林-森の島","en":"Forest - Forest Island","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/1004.PNG",
 auth:false
},
{
 name:"積み木アカイトトンボ(虹)",
 nameI18n:{"ja":"積み木アカイトトンボ(虹)","en":"Building Block Small Red Damselfly (Rainbow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:110,
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"特殊積み木虫クエスト",
 locationI18n:{"ja":"特殊積み木虫クエスト","en":"Special Building Block Bug Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"bugs/1005.PNG",
 auth:false
}
 // ここに追加していく
].map((c,i) => ({
  ...c,
  type:"bug",
  bookIndex:i
}));
