// Q&Aデータ 
// category: "question" = 質問, "request" = 要望, "bug" = 不具合
// status  : "fixed"(修正済み) / "progress"(対応中) / "considering"(検討中) / "wontfix"(対応見送り)
//           質問カテゴリにはstatus不要（null推奨）
// answer内で改行したい場合は \n を使ってください

const faqData = [
  {
    id: 1,
    category: "request",
    question: "ひらがなでも名前検索できるようにして欲しいです！",
    questionI18n:{"ja":"ひらがなでも名前検索できるようにして欲しいです！","en":"I'd like to be able to search names in hiragana too!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！ですが、現時点では『ひらがな検索』を追加する予定はないです🙇‍♂️",
    answerI18n:{"ja":"ご要望ありがとうございます！ですが、現時点では『ひらがな検索』を追加する予定はないです🙇‍♂️","en":"Thank you for the suggestion! However, we don't currently have plans to add hiragana search 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },
  {
    id: 2,
    category: "bug",
    question: "今の天気でしか出現しないのボタンを押すと何も表示されません。雨の日でも何も出ない状態ですがなにか設定の仕方に問題がありますでしょうか？",
    questionI18n:{"ja":"今の天気でしか出現しないのボタンを押すと何も表示されません。雨の日でも何も出ない状態ですがなにか設定の仕方に問題がありますでしょうか？","en":"When I press the button for 'only appears in current weather', nothing shows up. Nothing appears even on rainy days — is something wrong with the settings?","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "こちらサイト移行時に修正致しました！晴れの時にこのボタンを押すと、晴れ・虹のものだけが表示されます(全天気、雨は非表示)！",
    answerI18n:{"ja":"こちらサイト移行時に修正致しました！晴れの時にこのボタンを押すと、晴れ・虹のものだけが表示されます(全天気、雨は非表示)！","en":"This was fixed during the site migration! When it's sunny and you press this button, only sunny/rainbow items will show (all-weather and rain items are hidden)!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 3,
    category: "request",
    question: "天気ごとに検索できたらとても助かります！",
    questionI18n:{"ja":"天気ごとに検索できたらとても助かります！","en":"It would help a lot if I could search by weather!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！出現するものか出現しないものかが天気で分かれており、実質天気ごとに検索しているのと大差がないと考えているので現時点では『天気ごとに検索』は追加する予定はないです🥲",
    answerI18n:{"ja":"ご要望ありがとうございます！出現するものか出現しないものかが天気で分かれており、実質天気ごとに検索しているのと大差がないと考えているので現時点では『天気ごとに検索』は追加する予定はないです🥲","en":"Thank you for the suggestion! Since items are already split into 'appearing' and 'not appearing' based on weather, we feel this is effectively the same as searching by weather, so we don't currently plan to add a 'search by weather' feature 🥲","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },
  {
    id: 4,
    category: "bug",
    question: "⭐︎マークはお気に入りボタンかと思ったのですが、認証の判定になっているようです。したの認証マークを押しても、認証扱いになりませんでした。",
    questionI18n:{"ja":"⭐︎マークはお気に入りボタンかと思ったのですが、認証の判定になっているようです。したの認証マークを押しても、認証扱いになりませんでした。","en":"I thought the ⭐︎ mark was a favorite button, but it seems to be treated as verification. Even when I pressed the verification mark below it, it wasn't counted as verified.","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "⭐️マークは、星5までGETしたら押すことを想定しており、🎖(認証)マークは、認証マスターをGETしたら押すことを想定しております！こちらで再度確認致しましたが、正常に動作しておりました🙇‍♂️",
    answerI18n:{"ja":"⭐️マークは、星5までGETしたら押すことを想定しており、🎖(認証)マークは、認証マスターをGETしたら押すことを想定しております！こちらで再度確認致しましたが、正常に動作しておりました🙇‍♂️","en":"The ⭐️ mark is meant to be pressed once you get to ★5, and the 🎖 (verification) mark is meant to be pressed once you get Verified Master! We checked again on our end and it was working correctly 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },
  {
    id: 5,
    category: "bug",
    question: "魚　何匹か抜けてるので修正お願いします",
    questionI18n:{"ja":"魚　何匹か抜けてるので修正お願いします","en":"Some fish seem to be missing, please fix it","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "こちらの図鑑は、現在の時刻と天気に出現するものだけが表示されており、該当しないものは出現しないの方に表示されております！一応ゲーム内の図鑑と照らし合わせた後、魚は全て掲載しているはずですが、抜けがあれば魚の名前を教えてくださるとありがたいです！",
    answerI18n:{"ja":"こちらの図鑑は、現在の時刻と天気に出現するものだけが表示されており、該当しないものは出現しないの方に表示されております！一応ゲーム内の図鑑と照らし合わせた後、魚は全て掲載しているはずですが、抜けがあれば魚の名前を教えてくださるとありがたいです！","en":"This encyclopedia only shows items that appear at the current time and weather — anything that doesn't match is shown under 'Not currently appearing'! We double-checked against the in-game encyclopedia and all fish should be listed, but if any are missing, please let us know the fish's name!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 6,
    category: "request",
    question: "園芸やレシピもあると嬉しいです🥰",
    questionI18n:{"ja":"園芸やレシピもあると嬉しいです🥰","en":"It would be great to have gardening and recipes too 🥰","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "こちら2026/06/25 19:00に追加完了致しました🙇‍♂️",
    answerI18n:{"ja":"こちら2026/06/25 19:00に追加完了致しました🙇‍♂️","en":"This was added on 2026/06/25 at 19:00 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 7,
    category: "bug",
    question: "サバとリュウグウノツカイが表示されてないです",
    questionI18n:{"ja":"サバとリュウグウノツカイが表示されてないです","en":"Mackerel and Oarfish aren't showing up","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "こちらは不具合ではなく、その時の時間に出現していないものも、『出現しない』の方に表示されます！サバとリュウグウノツカイのデータは入っています！",
    answerI18n:{"ja":"こちらは不具合ではなく、その時の時間に出現していないものも、『出現しない』の方に表示されます！サバとリュウグウノツカイのデータは入っています！","en":"This isn't a bug — items that don't appear at that particular time are shown under 'Not currently appearing'! The data for Mackerel and Oarfish is included!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },
  {
    id: 8,
    category: "request",
    question: "コンプ状況シェアの画像に、認証も虫魚野鳥に分けた個数も表示してもらえたらうれしいです！",
    questionI18n:{"ja":"コンプ状況シェアの画像に、認証も虫魚野鳥に分けた個数も表示してもらえたらうれしいです！","en":"It'd be great if the completion-status share image also showed verified counts broken down by bugs/fish/birds!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！こちら追加すると良さそうですね！追加検討いたします！ありがとうございます🙇‍♂️",
    answerI18n:{"ja":"ご要望ありがとうございます！こちら追加すると良さそうですね！追加検討いたします！ありがとうございます🙇‍♂️","en":"Thank you for the suggestion! That does sound like a good addition! We'll consider adding it! Thank you 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "considering",
  },
  {
    id: 9,
    category: "bug",
    question: "天気が違う時があります。あと、今出現しているものがすごく少なくなってます！",
    questionI18n:{"ja":"天気が違う時があります。あと、今出現しているものがすごく少なくなってます！","en":"Sometimes the weather is wrong. Also, the number of things currently appearing has gotten really small!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご報告ありがとうございます！申し訳ございませんтт天気のデータを変え忘れていました。こちらは都度チェックするように致します！出現しているものに関しては、レベル範囲のスライダーで範囲を狭めてしまってないかの確認をしてくださるといいかもしれないです！",
    answerI18n:{"ja":"ご報告ありがとうございます！申し訳ございませんтт天気のデータを変え忘れていました。こちらは都度チェックするように致します！出現しているものに関しては、レベル範囲のスライダーで範囲を狭めてしまってないかの確認をしてくださるといいかもしれないです！","en":"Thank you for the report! I'm sorry — I forgot to update the weather data. I'll make sure to check this each time from now on! As for the low number of items appearing, it might help to check whether the level range slider has been narrowed down!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 10,
    category: "request",
    question: "料理はカチカチする回数の表示があると嬉しいです！",
    questionI18n:{"ja":"料理はカチカチする回数の表示があると嬉しいです！","en":"It'd be nice if recipes showed how many times you need to tap!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！こちらレベルによって回数が変わるので少し悩んでいます💦追加検討はします！ありがとうございます*^^*",
    answerI18n:{"ja":"ご要望ありがとうございます！こちらレベルによって回数が変わるので少し悩んでいます💦追加検討はします！ありがとうございます*^^*","en":"Thank you for the suggestion! Since the number of taps changes depending on level, I'm a bit torn on this 💦 I'll consider adding it! Thank you *^^*","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "considering",
  },
  {
    id: 11,
    category: "request",
    question: "ワンちゃん猫ちゃんの好きな物探しリストが追加されたら嬉しいです！",
    questionI18n:{"ja":"ワンちゃん猫ちゃんの好きな物探しリストが追加されたら嬉しいです！","en":"It'd be great if a list for finding what dogs and cats like was added!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！こちら追加する予定はありますが、少し時間がかかるのでお待ちください！ありがとうございます🙇‍♂️",
    answerI18n:{"ja":"ご要望ありがとうございます！こちら追加する予定はありますが、少し時間がかかるのでお待ちください！ありがとうございます🙇‍♂️","en":"Thank you for the suggestion! We do plan to add this, but it'll take a bit of time, so please wait! Thank you 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "considering",
  },
  {
    id: 12,
    category: "bug",
    question: "設定から「通知を許可」にしているのに、アプリでは「先に通知を許可してください」と表示されてしまって、作物の通知が受け取れません...🥲",
    questionI18n:{"ja":"設定から「通知を許可」にしているのに、アプリでは「先に通知を許可してください」と表示されてしまって、作物の通知が受け取れません...🥲","en":"Even though I've allowed notifications in Settings, the app still shows 'Please allow notifications first' and I can't receive crop notifications...🥲","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "こちら修正致しました！本体の設定で『はとぴ図鑑』の通知を許可したあと再度開き直してご確認ください！",
    answerI18n:{"ja":"こちら修正致しました！本体の設定で『はとぴ図鑑』の通知を許可したあと再度開き直してご確認ください！","en":"This has been fixed! Please allow notifications for 'Hatopi Encyclopedia' in your device settings, then reopen the app and check again!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 13,
    category: "question",
    question: "料理の調理時間はなにを目安にしていますでしょうか？",
    questionI18n:{"ja":"料理の調理時間はなにを目安にしていますでしょうか？","en":"What is the cooking time for recipes based on?","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "調理時間は、その料理に使う作物の成長にかかる時を書いていみてますтт",
    answerI18n:{"ja":"調理時間は、その料理に使う作物の成長にかかる時を書いていみてますтт","en":"The cooking time is based on the growth time of the crops used in that recipe ;;","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: null,
  },
  {
    id: 14,
    category: "request",
    question: "料理はカチカチする回数の表示があると嬉しいです！",
    questionI18n:{"ja":"料理はカチカチする回数の表示があると嬉しいです！","en":"It'd be nice if recipes showed how many times you need to tap!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！料理1回すれば何回タップが必要か分かるという観点から今回は見送らせていただきます🥲",
    answerI18n:{"ja":"ご要望ありがとうございます！料理1回すれば何回タップが必要か分かるという観点から今回は見送らせていただきます🥲","en":"Thank you for the suggestion! Since you can find out how many taps are needed just by cooking once, we'll be passing on this for now 🥲","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },
  {
    id: 15,
    category: "request",
    question: "一匹沸きの虫や鳥のリポップタイマーがあると嬉しいです。検討頂けないでしょうか。",
    questionI18n:{"ja":"一匹沸きの虫や鳥のリポップタイマーがあると嬉しいです。検討頂けないでしょうか。","en":"It'd be nice to have a respawn timer for single-spawn bugs and birds. Could you consider it?","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "基本的に、虫はほとんど『1分』、野鳥は長くても『5分』なのでそれを覚えておくといいかもしれないです🥲探す時間やタイマー起動するタイミングでズレてしまうと思うので、現時点ではこちらの追加は見送らせて頂きます💦",
    answerI18n:{"ja":"基本的に、虫はほとんど『1分』、野鳥は長くても『5分』なのでそれを覚えておくといいかもしれないです🥲探す時間やタイマー起動するタイミングでズレてしまうと思うので、現時点ではこちらの追加は見送らせて頂きます💦","en":"Basically, bugs respawn in about '1 minute' and birds take at most '5 minutes', so it might help to just keep that in mind 🥲 Since search time and when you start the timer would cause discrepancies, we'll be passing on adding this for now 💦","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },  
  {
    id: 16,
    category: "request",
    question: "星マークと認証マークとは別で、図鑑が埋まっているか(対象の虫や魚等がゲットできたか)もチェック出来るようになるととても嬉しいです！虹限定やレベル不足でまだ図鑑が解放されていないものもチェックしておけたら分かりやすいので。",
    questionI18n:{"ja":"星マークと認証マークとは別で、図鑑が埋まっているか(対象の虫や魚等がゲットできたか)もチェック出来るようになるととても嬉しいです！虹限定やレベル不足でまだ図鑑が解放されていないものもチェックしておけたら分かりやすいので。","en":"Separate from the star and verification marks, it'd be great to also be able to check whether an encyclopedia entry is filled in (whether you've gotten that bug/fish/etc.). It would make things clearer to also be able to check items that haven't been unlocked yet due to rainbow-only conditions or insufficient level.","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！ですが、結構ごちゃごちゃしてしまうのかな考えており、現時点では追加する予定は無いです🥺",
    answerI18n:{"ja":"ご要望ありがとうございます！ですが、結構ごちゃごちゃしてしまうのかな考えており、現時点では追加する予定は無いです🥺","en":"Thank you for the suggestion! However, we think it might make things pretty cluttered, so we don't currently plan to add this 🥺","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },  
  {
    id: 17,
    category: "request",
    question: "猫のエサ、シマスズメダイが抜けているので追加お願いします",
    questionI18n:{"ja":"猫のエサ、シマスズメダイが抜けているので追加お願いします","en":"Sergeant Major Damselfish is missing from cat food, please add it","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご報告ありがとうございます！レベル10までのものしか追加していなかったので助かりました！他にもあれば教えてください🙇‍♂️",
    answerI18n:{"ja":"ご報告ありがとうございます！レベル10までのものしか追加していなかったので助かりました！他にもあれば教えてください🙇‍♂️","en":"Thank you for the report! I had only added items up to level 10, so this was really helpful! Please let us know if there are others too 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 18,
    category: "request",
    question: "ペットの名前を1匹1匹個別に変えられたら嬉しいです！",
    questionI18n:{"ja":"ペットの名前を1匹1匹個別に変えられたら嬉しいです！","en":"It'd be nice to be able to change each pet's name individually!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "こちら既に実装済みです！ペット1と書いてある場所を素早く『ダブルタップ』することで個別に名前変更ができるようになっております！",
    answerI18n:{"ja":"こちら既に実装済みです！ペット1と書いてある場所を素早く『ダブルタップ』することで個別に名前変更ができるようになっております！","en":"This has already been implemented! You can change each pet's name individually by quickly 'double-tapping' where it says 'Pet 1'!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 19,
    category: "request",
    question: "iPhoneのSEでこちらのサイトを見るときに、最初にポップアップされる不具合、追加情報が大きくてOkがどうしても下のブックマーク等あるところと干渉してしまってしてしまって押すことができず図鑑を開くことができません。別途✖️ボタンかボタンか1画面の半分くらいのポップアップだと嬉しいです。",
    questionI18n:{"ja":"iPhoneのSEでこちらのサイトを見るときに、最初にポップアップされる不具合、追加情報が大きくてOkがどうしても下のブックマーク等あるところと干渉してしまってしてしまって押すことができず図鑑を開くことができません。別途✖️ボタンかボタンか1画面の半分くらいのポップアップだと嬉しいです。","en":"When viewing this site on an iPhone SE, the bug/update-info popup that appears first is too large, and the OK button ends up overlapping with the bookmark bar area at the bottom, so I can't press it and can't open the encyclopedia. It would be nice to have a separate ✕ button, or a popup that's only about half the screen.","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご丁寧にありがとうございます！こちら6/30に修正致しましたが、ホーム画面追加されてない場合はまだ押せないのかもしれないです🥲今後追加情報出す際には、長さを配慮致します🙇‍♂️",
    answerI18n:{"ja":"ご丁寧にありがとうございます！こちら6/30に修正致しましたが、ホーム画面追加されてない場合はまだ押せないのかもしれないです🥲今後追加情報出す際には、長さを配慮致します🙇‍♂️","en":"Thank you so much for the detailed report! This was fixed on 6/30, but if the site hasn't been added to your home screen, it might still not be pressable 🥲 We'll be mindful of the length when posting update info in the future 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },  
  {
    id: 20,
    category: "request",
    question: "毎日のツルツルオ－クの木と蛍石の番地を載せて欲しいです！",
    questionI18n:{"ja":"毎日のツルツルオ－クの木と蛍石の番地を載せて欲しいです！","en":"I'd like the daily locations for Smooth Oak trees and fluorite to be posted!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！こちら追加したいと思ってます！少々お待ちください😊",
    answerI18n:{"ja":"ご要望ありがとうございます！こちら追加したいと思ってます！少々お待ちください😊","en":"Thank you for the suggestion! We'd like to add this! Please wait a little while 😊","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "progress",
  }, 
  {
    id: 21,
    category: "bug",
    question: "以前のペットの好物と嫌いなものを確認するリストページを利用しており、今回の新しいサイトの方にデータを引き継いで使おうと思ったところ、前回のページとデータが変わってしまった…あげてない魚があげたことになり、好物が別のもので表示されている…前回のページももう見れないしとても困ります。",
    questionI18n:{"ja":"以前のペットの好物と嫌いなものを確認するリストページを利用しており、今回の新しいサイトの方にデータを引き継いで使おうと思ったところ、前回のページとデータが変わってしまった…あげてない魚があげたことになり、好物が別のもので表示されている…前回のページももう見れないしとても困ります。","en":"I was using the previous list page for checking my pets' likes and dislikes, and when I tried to carry the data over to the new site, the data changed from the previous page... fish I hadn't fed show as fed, and favorites are showing as different items... I also can't view the previous page anymore, so this is really troubling.","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ペットページで使用しているページ内でのみデータが保存される仕様なっているため、引き継いだら全く別のデータになる事は有り得ないです🥲異端末間でも正常に引き継げることも実装前に確認済みですので、データが変わってしまうことは無いと思われます；；お手数ですがもう一度入力し直して頂けると幸いです🙇‍♂️もし新しい方でも記録していて、旧サイトから引き継いだ後に新しい方で記録していたものが消えてしまった場合は、データが上書きされるため正常な動作になっております。",
    answerI18n:{"ja":"ペットページで使用しているページ内でのみデータが保存される仕様なっているため、引き継いだら全く別のデータになる事は有り得ないです🥲異端末間でも正常に引き継げることも実装前に確認済みですので、データが変わってしまうことは無いと思われます；；お手数ですがもう一度入力し直して頂けると幸いです🙇‍♂️もし新しい方でも記録していて、旧サイトから引き継いだ後に新しい方で記録していたものが消えてしまった場合は、データが上書きされるため正常な動作になっております。","en":"The pet page is designed so that data is only saved within that page itself, so it shouldn't be possible for the data to become something completely different after carrying it over 🥲 We also confirmed before release that data carries over correctly between different devices, so we don't believe the data would have changed ;; We're sorry for the trouble, but we'd appreciate it if you could re-enter the information again 🙇‍♂️ If you had also been recording data on the new page, and what you'd recorded there disappeared after carrying over from the old site, that's expected behavior since the data gets overwritten.","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "wontfix",
  },
  {
    id: 23,
    category: "question",
    question: "サイトからアプリへの追加の仕方を教えてください",
    questionI18n:{"ja":"サイトからアプリへの追加の仕方を教えてください","en":"Please tell me how to add this site as an app","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご質問ありがとうございます🙇‍♂️「Safari」にて当サイトを開いていただき、「共有ボタン(シェアボタン)」を押した後に出てくるものを少し下にスクロールしていただくと、「ホーム画面に追加」の項目があると思いますので、そちらから「webアプリ」の項目にチェックを入れたままホーム画面に追加してください！",
    answerI18n:{"ja":"ご質問ありがとうございます🙇‍♂️「Safari」にて当サイトを開いていただき、「共有ボタン(シェアボタン)」を押した後に出てくるものを少し下にスクロールしていただくと、「ホーム画面に追加」の項目があると思いますので、そちらから「webアプリ」の項目にチェックを入れたままホーム画面に追加してください！","en":"Thank you for the question 🙇‍♂️ Please open this site in Safari, tap the 'Share' button, and scroll down a little in the menu that appears — you should find an option called 'Add to Home Screen'. From there, please add it to your home screen while leaving the 'Web App' option checked!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: null,
  },    
  {
    id: 24,
    category: "bug",
    question: "ジンベエザメの出現時間は0~12,18~0が正しいのですが、0~6,18~0になってしまっています！m(_ _)m／ジンベイザメの出現時間のうち、6-12が抜けていると思います。",
    questionI18n:{"ja":"ジンベエザメの出現時間は0~12,18~0が正しいのですが、0~6,18~0になってしまっています！m(_ _)m／ジンベイザメの出現時間のうち、6-12が抜けていると思います。","en":"The Whale Shark's appearance time should correctly be 0~12, 18~0, but it's showing as 0~6, 18~0! m(_ _)m / I think 6-12 is missing from the Whale Shark's appearance time.","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "複数ご報告ありがとうございます！こちら修正致しました。間違えており申し訳ございませんでした🙇‍♂️",
    answerI18n:{"ja":"複数ご報告ありがとうございます！こちら修正致しました。間違えており申し訳ございませんでした🙇‍♂️","en":"Thank you for the multiple reports! This has been fixed. I apologize for the mistake 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 25,
    category: "bug",
    question: "再度すみません…。アジアアロワナの出現時間は0~18ではなく、0~12,18~0です！",
    questionI18n:{"ja":"再度すみません…。アジアアロワナの出現時間は0~18ではなく、0~12,18~0です！","en":"Sorry again... The Asian Arowana's appearance time isn't 0~18, it's 0~12, 18~0!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "再三にわたってありがとうございます🙇‍♂️こちらも修正致しました。他のデータも今一度確認し直しておきます！",
    answerI18n:{"ja":"再三にわたってありがとうございます🙇‍♂️こちらも修正致しました。他のデータも今一度確認し直しておきます！","en":"Thank you so much for reporting again and again 🙇‍♂️ This has also been fixed. I'll go back and double-check the other data too!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 26,
    category: "request",
    question: "濃厚ミルクティーとかココアミルクティーのレシピほしい！！！",
    questionI18n:{"ja":"濃厚ミルクティーとかココアミルクティーのレシピほしい！！！","en":"I want recipes for things like Rich Milk Tea and Cocoa Milk Tea!!!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！レベル11〜レベル13までの料理を追加しました！画像は持っていないのでNo imageばかりですみません😢",
    answerI18n:{"ja":"ご要望ありがとうございます！レベル11〜レベル13までの料理を追加しました！画像は持っていないのでNo imageばかりですみません😢","en":"Thank you for the suggestion! We've added recipes for levels 11 through 13! We don't have the images yet so most show 'No image', sorry 😢","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 27,
    category: "bug",
    question: "7月5日の朝にサイトを見たところ、ペットの好物が入り乱れているようです。具体的には、好物登録していた魚が別の魚になっていたり、既にあげた魚をあげていないことになったりなどです。使用端末はiPhone、サイトをホームに追加しアプリとして使用しています。対処法等あればご指示して頂きたいです。",
    questionI18n:{"ja":"7月5日の朝にサイトを見たところ、ペットの好物が入り乱れているようです。具体的には、好物登録していた魚が別の魚になっていたり、既にあげた魚をあげていないことになったりなどです。使用端末はiPhone、サイトをホームに追加しアプリとして使用しています。対処法等あればご指示して頂きたいです。","en":"When I checked the site on the morning of July 5th, my pets' favorites seem to be mixed up. Specifically, fish I had registered as favorites had changed to different fish, and fish I had already fed showed as not fed, among other things. I'm using an iPhone, with the site added to my home screen as an app. If there's a fix, I'd appreciate instructions.","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご報告ありがとうございます。こちら症状など確認いたします。少々お待ちください🙇‍♂️",
    answerI18n:{"ja":"ご報告ありがとうございます。こちら症状など確認いたします。少々お待ちください🙇‍♂️","en":"Thank you for the report. We'll look into the symptoms. Please wait a little while 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "progress",
  },
  {
    id: 28,
    category: "bug",
    question: "天気が不明になっていて次の所も不明になっていて、虫、魚、野鳥全て何も表示がされません。",
    questionI18n:{"ja":"天気が不明になっていて次の所も不明になっていて、虫、魚、野鳥全て何も表示がされません。","en":"The weather is showing as unknown, and the 'next' weather is also unknown, so nothing shows up at all for bugs, fish, or birds.","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご報告ありがとうございます！天気のデータを変更し忘れていましたすみません😢以後気をつけますのでご容赦ください🙇‍♂️",
    answerI18n:{"ja":"ご報告ありがとうございます！天気のデータを変更し忘れていましたすみません😢以後気をつけますのでご容赦ください🙇‍♂️","en":"Thank you for the report! I forgot to update the weather data, I'm sorry 😢 I'll be more careful going forward, thank you for your understanding 🙇‍♂️","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  {
    id: 29,
    category: "request",
    question: "大変かとは思いますが、ペットの名前を入れれるようにして頂けたると嬉しいです！",
    questionI18n:{"ja":"大変かとは思いますが、ペットの名前を入れれるようにして頂けたると嬉しいです！","en":"I know it might be a lot of work, but it'd be great if you could make it possible to enter pet names!","zh-CN":"","zh-TW":"","ko":"","th":""},
    answer: "ご要望ありがとうございます！こちら既に実装されています！「ペット1」の場所をダブルタップしていただくと名前変更が可能になっています！",
    answerI18n:{"ja":"ご要望ありがとうございます！こちら既に実装されています！「ペット1」の場所をダブルタップしていただくと名前変更が可能になっています！","en":"Thank you for the suggestion! This has already been implemented! You can change the name by double-tapping where it says 'Pet 1'!","zh-CN":"","zh-TW":"","ko":"","th":""},
    status: "fixed",
  },
  // 以下、追加していく
  // {
  //   id: 4,
  //   category: "question",
  //   question: "",
  //   answer: "",
  //   status: null,
  // },
];
