// 野鳥
const birdData = [
{
 name:"コマドリ",
 nameI18n:{"ja":"コマドリ","en":"Japanese Robin","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:7,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"中心街",
 locationI18n:{"ja":"中心街","en":"Downtown","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/001.PNG"
},
{
 name:"シジュウカラ",
 nameI18n:{"ja":"シジュウカラ","en":"Japanese Tit","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:7,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山",
 locationI18n:{"ja":"温泉山","en":"Hot Spring Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/002.PNG"
},
{
 name:"ミソサザイ",
 nameI18n:{"ja":"ミソサザイ","en":"Eurasian Wren","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:7,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林",
 locationI18n:{"ja":"森林","en":"Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/003.PNG"
},
{
 name:"ウソ",
 nameI18n:{"ja":"ウソ","en":"Eurasian Bullfinch","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:7,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/004.PNG"
},
{
 name:"ズアオアトリ",
 nameI18n:{"ja":"ズアオアトリ","en":"Common Chaffinch","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:7,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑",
 locationI18n:{"ja":"花畑","en":"Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/005.PNG"
},
{
 name:"ルリコンゴウインコ",
 nameI18n:{"ja":"ルリコンゴウインコ","en":"Blue-and-yellow Macaw","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:7,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト",
 locationI18n:{"ja":"巣ごもりクエスト","en":"Nesting Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/006.PNG"
},
{
 name:"ヒメモリバト",
 nameI18n:{"ja":"ヒメモリバト","en":"Stock Dove","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"中心街",
 locationI18n:{"ja":"中心街","en":"Downtown","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/007.PNG"
},
{
 name:"シラコバト",
 nameI18n:{"ja":"シラコバト","en":"Eurasian Collared Dove","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"ホーム",
 locationI18n:{"ja":"ホーム","en":"Home","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/008.PNG"
},
{
 name:"ソデグロバト",
 nameI18n:{"ja":"ソデグロバト","en":"White-winged Pigeon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村",
 locationI18n:{"ja":"漁村","en":"Fishing Village","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/009.PNG"
},
{
 name:"オオフラミンゴ",
 nameI18n:{"ja":"オオフラミンゴ","en":"Greater Flamingo","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:15,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"水辺",
 locationI18n:{"ja":"水辺","en":"Waterside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/010.PNG"
},
{
 name:"インドクジャク",
 nameI18n:{"ja":"インドクジャク","en":"Indian Peafowl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト",
 locationI18n:{"ja":"巣ごもりクエスト","en":"Nesting Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/011.PNG"
},
{
 name:"マガモ",
 nameI18n:{"ja":"マガモ","en":"Mallard","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:1,
 price:12,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"湖",
 locationI18n:{"ja":"湖","en":"Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/012.PNG"
},
{
 name:"エナガ",
 nameI18n:{"ja":"エナガ","en":"Long-tailed Tit","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:2,
 star5:"全天気 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"ブランクの頭上",
 locationI18n:{"ja":"ブランクの頭上","en":"Above Blanc","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/013.PNG",
 auth:false
},
{
 name:"ゴジュウカラ",
 nameI18n:{"ja":"ゴジュウカラ","en":"Eurasian Nuthatch","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村",
 locationI18n:{"ja":"漁村","en":"Fishing Village","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/014.PNG"
},
{
 name:"ヒゲガラ",
 nameI18n:{"ja":"ヒゲガラ","en":"Bearded Reedling","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山",
 locationI18n:{"ja":"温泉山","en":"Hot Spring Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/015.PNG"
},
{
 name:"ズアカモズ",
 nameI18n:{"ja":"ズアカモズ","en":"Woodchat Shrike","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/016.PNG"
},
{
 name:"ウォンガバト",
 nameI18n:{"ja":"ウォンガバト","en":"Wonga Pigeon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:15,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林",
 locationI18n:{"ja":"森林","en":"Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/017.PNG"
},
{
 name:"コアオバト",
 nameI18n:{"ja":"コアオバト","en":"Little Green Pigeon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:15,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑",
 locationI18n:{"ja":"花畑","en":"Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/018.PNG"
},
{
 name:"ヒドリガモ",
 nameI18n:{"ja":"ヒドリガモ","en":"Eurasian Wigeon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:17,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"川",
 locationI18n:{"ja":"川","en":"River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/019.PNG"
},
{
 name:"カモメ",
 nameI18n:{"ja":"カモメ","en":"Common Gull","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:2,
 price:17,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海辺",
 locationI18n:{"ja":"海辺","en":"Seaside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/020.PNG"
},
{
 name:"ニシコウライウグイス",
 nameI18n:{"ja":"ニシコウライウグイス","en":"Eurasian Golden Oriole","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"ホーム",
 locationI18n:{"ja":"ホーム","en":"Home","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/021.PNG"
},
{
 name:"カノコスズメ",
 nameI18n:{"ja":"カノコスズメ","en":"Scaly-breasted Munia","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村-灯台",
 locationI18n:{"ja":"漁村-灯台","en":"Fishing Village - Lighthouse","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/022.PNG"
},
{
 name:"シマエナガ",
 nameI18n:{"ja":"シマエナガ","en":"Japanese Long-tailed Tit","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-ジャンプステージ",
 locationI18n:{"ja":"森林-ジャンプステージ","en":"Forest - Jump Stage","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/023.PNG"
},
{
 name:"ベニコンゴウインコ",
 nameI18n:{"ja":"ベニコンゴウインコ","en":"Scarlet Macaw","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト",
 locationI18n:{"ja":"巣ごもりクエスト","en":"Nesting Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/024.PNG"
},
{
 name:"アカツクシガモ",
 nameI18n:{"ja":"アカツクシガモ","en":"Ruddy Shelduck","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:17,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖街",
 locationI18n:{"ja":"郊外の湖街","en":"Suburban Lake Town","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/025.PNG"
},
{
 name:"ケワタガモ",
 nameI18n:{"ja":"ケワタガモ","en":"Common Eider","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:17,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"川",
 locationI18n:{"ja":"川","en":"River","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/026.PNG"
},
{
 name:"オデュアンカモメ",
 nameI18n:{"ja":"オデュアンカモメ","en":"Audouin's Gull","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:17,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"クジラ海の海辺",
 locationI18n:{"ja":"クジラ海の海辺","en":"Whale Sea Seaside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/027.PNG"
},
{
 name:"ヨーロッパヒメウ",
 nameI18n:{"ja":"ヨーロッパヒメウ","en":"European Shag","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:3,
 price:17,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"海",
 locationI18n:{"ja":"海","en":"Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/028.PNG"
},
{
 name:"タイリクハクセキレイ",
 nameI18n:{"ja":"タイリクハクセキレイ","en":"White Wagtail","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-パープルビーチ",
 locationI18n:{"ja":"花畑-パープルビーチ","en":"Flower Field - Purple Beach","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/029.PNG"
},
{
 name:"ハイズキンダルマエナガ",
 nameI18n:{"ja":"ハイズキンダルマエナガ","en":"Gray-hooded Bushtit","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村-漁村広場",
 locationI18n:{"ja":"漁村-漁村広場","en":"Fishing Village - Village Square","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/030.PNG"
},
{
 name:"ギンザンマシコ",
 nameI18n:{"ja":"ギンザンマシコ","en":"Pine Grosbeak","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-森の島",
 locationI18n:{"ja":"森林-森の島","en":"Forest - Forest Island","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/031.PNG"
},
{
 name:"フウチョウモドキ",
 nameI18n:{"ja":"フウチョウモドキ","en":"Bowerbird","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/032.PNG"
},
{
 name:"キンミノヒメアオバト",
 nameI18n:{"ja":"キンミノヒメアオバト","en":"Golden-mantled Green Pigeon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:17,
 star5:"雨・虹 /全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-風車の花畑",
 locationI18n:{"ja":"花畑-風車の花畑","en":"Flower Field - Windmill Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/033.PNG"
},
{
 name:"ギンケイ",
 nameI18n:{"ja":"ギンケイ","en":"Silver Pheasant","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:17,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-遺跡",
 locationI18n:{"ja":"温泉山-遺跡","en":"Hot Spring Mountain - Ruins","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/034.PNG"
},
{
 name:"ミコアイサ",
 nameI18n:{"ja":"ミコアイサ","en":"Smew","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:4,
 price:22,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森の湖",
 locationI18n:{"ja":"森の湖","en":"Forest Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/035.PNG"
},
{
 name:"キバラメジロハエトリ",
 nameI18n:{"ja":"キバラメジロハエトリ","en":"Yellow-bellied Flycatcher","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村-波止場",
 locationI18n:{"ja":"漁村-波止場","en":"Fishing Village - Pier","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/036.PNG"
},
{
 name:"ヨーロッパハチクイ",
 nameI18n:{"ja":"ヨーロッパハチクイ","en":"European Bee-eater","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:22,
 star5:"虹 / 6〜0",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山の湖畔",
 locationI18n:{"ja":"温泉山の湖畔","en":"Hot Spring Mountain Lakeside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/037.PNG"
},
{
 name:"ヒワコンゴウインコ",
 nameI18n:{"ja":"ヒワコンゴウインコ","en":"Green-winged Macaw","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト",
 locationI18n:{"ja":"巣ごもりクエスト","en":"Nesting Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/038.PNG"
},
{
 name:"オリーブバト",
 nameI18n:{"ja":"オリーブバト","en":"Olive Pigeon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:27,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-温泉",
 locationI18n:{"ja":"温泉山-温泉","en":"Hot Spring Mountain - Hot Spring","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/039.PNG"
},
{
 name:"コフラミンゴ",
 nameI18n:{"ja":"コフラミンゴ","en":"Lesser Flamingo","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:27,
 star5:"虹 / 6〜0",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森の湖畔",
 locationI18n:{"ja":"森の湖畔","en":"Forest Lakeside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/040.PNG"
},
{
 name:"クロアジサシ",
 nameI18n:{"ja":"クロアジサシ","en":"Sooty Tern","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:5,
 price:22,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"旧海の海辺",
 locationI18n:{"ja":"旧海の海辺","en":"Old Sea Seaside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/041.PNG"
},
{
 name:"シメ",
 nameI18n:{"ja":"シメ","en":"Hawfinch","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:15,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-火山湖",
 locationI18n:{"ja":"温泉山-火山湖","en":"Hot Spring Mountain - Volcanic Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/042.PNG"
},
{
 name:"キンムネバト",
 nameI18n:{"ja":"キンムネバト","en":"Golden-breasted Dove","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:27,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村-漁村東桟橋",
 locationI18n:{"ja":"漁村-漁村東桟橋","en":"Fishing Village - East Pier","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/043.PNG"
},
{
 name:"チシマウガラス",
 nameI18n:{"ja":"チシマウガラス","en":"Red-faced Cormorant","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:22,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"旧海・クジラ海",
 locationI18n:{"ja":"旧海・クジラ海","en":"Old Sea / Whale Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/044.PNG"
},
{
 name:"トラフズク",
 nameI18n:{"ja":"トラフズク","en":"Long-eared Owl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:6,
 price:47,
 star5:"虹 / 6〜12, 18〜0",
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-石海岸の崖",
 locationI18n:{"ja":"温泉山-石海岸の崖","en":"Hot Spring Mountain - Rocky Coast Cliff","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/045.PNG"
},
{
 name:"ルリガラ",
 nameI18n:{"ja":"ルリガラ","en":"Azure Tit","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:22,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-風車の花畑",
 locationI18n:{"ja":"花畑-風車の花畑","en":"Flower Field - Windmill Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/046.PNG"
},
{
 name:"スミレコンゴウインコ",
 nameI18n:{"ja":"スミレコンゴウインコ","en":"Hyacinth Macaw","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:22,
 star5:"虹 / 18〜0",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト",
 locationI18n:{"ja":"巣ごもりクエスト","en":"Nesting Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/047.PNG"
},
{
 name:"ボタンバト",
 nameI18n:{"ja":"ボタンバト","en":"Diamond Dove","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:27,
 star5:"虹 / 6〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/048.PNG"
},
{
 name:"アジサシ",
 nameI18n:{"ja":"アジサシ","en":"Common Tern","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:35,
 star5:"虹 / 6〜18",
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海の海辺",
 locationI18n:{"ja":"東海の海辺","en":"East Sea Seaside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/049.PNG"
},
{
 name:"チョウゲンボウ",
 nameI18n:{"ja":"チョウゲンボウ","en":"Common Kestrel","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:7,
 price:47,
 star5:"虹 / 6〜0",
 weather:["晴れ","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-コジカ塔(木のてっぺん)",
 locationI18n:{"ja":"森林-コジカ塔(木のてっぺん)","en":"Forest - Fawn Tower (Treetop)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/050.PNG"
},
{
 name:"ルリツグミ",
 nameI18n:{"ja":"ルリツグミ","en":"Siberian Blue Robin","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:30,
 star5:"虹 / 18〜0",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/051.PNG"
},
{
 name:"ベニヒワ",
 nameI18n:{"ja":"ベニヒワ","en":"Common Redpoll","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:22,
 star5:"虹 / 12〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/052.PNG"
},
{
 name:"モモイロバト",
 nameI18n:{"ja":"モモイロバト","en":"Pink Pigeon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:27,
 star5:"虹 / 12〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-クジラ山",
 locationI18n:{"ja":"花畑-クジラ山","en":"Flower Field - Whale Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/053.PNG"
},
{
 name:"ハヤブサ",
 nameI18n:{"ja":"ハヤブサ","en":"Peregrine Falcon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:8,
 price:65,
 star5:"虹 / 18〜0 (6〜12？)",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-温泉(崖の上)",
 locationI18n:{"ja":"温泉山-温泉(崖の上)","en":"Hot Spring Mountain - Hot Spring (Cliff Top)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/054.PNG"
},
{
 name:"ナナイロフウキンチョウ",
 nameI18n:{"ja":"ナナイロフウキンチョウ","en":"Paradise Tanager","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:30,
 star5:"虹 / 18〜0",
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/055.PNG"
},
{
 name:"ベニイロフラミンゴ",
 nameI18n:{"ja":"ベニイロフラミンゴ","en":"American Flamingo","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:55,
 star5:"虹 / 12〜18",
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-パープルビーチ",
 locationI18n:{"ja":"花畑-パープルビーチ","en":"Flower Field - Purple Beach","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/056.PNG"
},
{
 name:"マクジャク",
 nameI18n:{"ja":"マクジャク","en":"Green Peafowl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:37,
 star5:"虹 / 12〜18 (18〜0？)",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト(追加段階)",
 locationI18n:{"ja":"巣ごもりクエスト(追加段階)","en":"Nesting Quest (Extra Stage)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/057.PNG"
},
{
 name:"カオジロオタテガモ",
 nameI18n:{"ja":"カオジロオタテガモ","en":"White-headed Duck","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:45,
 star5:"虹 / 12〜18",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山の湖",
 locationI18n:{"ja":"温泉山の湖","en":"Hot Spring Mountain Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/058.PNG"
},
{
 name:"インペリアルシャグ",
 nameI18n:{"ja":"インペリアルシャグ","en":"Imperial Shag","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:9,
 price:45,
 star5:"虹 / 12〜18",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"東海・そよ風の海",
 locationI18n:{"ja":"東海・そよ風の海","en":"East Sea / Breeze Sea","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/059.PNG"
},
{
 name:"アゾレスウソ",
 nameI18n:{"ja":"アゾレスウソ","en":"Azores Bullfinch","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:30,
 star5:"虹 / 18〜0",
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"漁村-灯台",
 locationI18n:{"ja":"漁村-灯台","en":"Fishing Village - Lighthouse","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/060.PNG"
},
{
 name:"ロクショウヒタキ",
 nameI18n:{"ja":"ロクショウヒタキ","en":"Verditer Flycatcher","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:30,
 star5:"虹 / 18〜0",
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-ジャンプステージ",
 locationI18n:{"ja":"森林-ジャンプステージ","en":"Forest - Jump Stage","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/061.PNG"
},
{
 name:"アカアシチョウゲンボウ",
 nameI18n:{"ja":"アカアシチョウゲンボウ","en":"Red-footed Falcon","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:65,
 star5:"虹 / 18〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-遺跡(崖の上)",
 locationI18n:{"ja":"温泉山-遺跡(崖の上)","en":"Hot Spring Mountain - Ruins (Cliff Top)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/062.PNG"
},
{
 name:"ワシミミズク",
 nameI18n:{"ja":"ワシミミズク","en":"Eurasian Eagle-Owl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:10,
 price:65,
 star5:"虹 / 18〜0",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"森林-コジカ塔(木のてっぺん)",
 locationI18n:{"ja":"森林-コジカ塔(木のてっぺん)","en":"Forest - Fawn Tower (Treetop)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/063.PNG"
}, 
{
 name:"コムクドリ",
 nameI18n:{"ja":"コムクドリ","en":"Chestnut-cheeked Starling","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 star5:"虹 / 18〜0",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"花畑-風車の花畑",
 locationI18n:{"ja":"花畑-風車の花畑","en":"Flower Field - Windmill Flower Field","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"クロヒゲバト",
 nameI18n:{"ja":"クロヒゲバト","en":"Black-collared Dove","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 star5:"虹 / 12〜0",
 weather:["晴れ","虹"],
 time:["12-18","18-0","0-6"],
 location:"郊外",
 locationI18n:{"ja":"郊外","en":"Suburbs","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"シロクジャク",
 nameI18n:{"ja":"シロクジャク","en":"White Peafowl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 star5:"虹 / 12〜18",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト(追加段階)",
 locationI18n:{"ja":"巣ごもりクエスト(追加段階)","en":"Nesting Quest (Extra Stage)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"トモエガモ",
 nameI18n:{"ja":"トモエガモ","en":"Baikal Teal","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 star5:"虹 / 12〜18",
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-火山湖",
 locationI18n:{"ja":"温泉山-火山湖","en":"Hot Spring Mountain - Volcanic Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
}, 
{
 name:"インカアジサシ",
 nameI18n:{"ja":"インカアジサシ","en":"Inca Tern","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:11,
 star5:"虹 / 6〜18",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"旧海の海辺",
 locationI18n:{"ja":"旧海の海辺","en":"Old Sea Seaside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ニシツノメドリ",
 nameI18n:{"ja":"ニシツノメドリ","en":"Atlantic Puffin","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 star5:"虹 / 6〜12",
 weather:["晴れ","虹"],
 time:["6-12","18-0","0-6"],
 location:"クジラ海の海辺",
 locationI18n:{"ja":"クジラ海の海辺","en":"Whale Sea Seaside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"フヨウチョウ",
 nameI18n:{"ja":"フヨウチョウ","en":"Bird-of-Paradise","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 star5:"虹 / 18〜0",
 weather:["虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山",
 locationI18n:{"ja":"温泉山","en":"Hot Spring Mountain","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"アオアシカツオドリ",
 nameI18n:{"ja":"アオアシカツオドリ","en":"Blue-footed Booby","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 star5:"虹 / 12〜18",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"そよ風の海の海辺",
 locationI18n:{"ja":"そよ風の海の海辺","en":"Breeze Sea Seaside","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"シロフクロウ",
 nameI18n:{"ja":"シロフクロウ","en":"Snowy Owl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:12,
 star5:"虹 / 18〜0",
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0"],
 location:"森林-不思議な松林",
 locationI18n:{"ja":"森林-不思議な松林","en":"Forest - Mysterious Pine Forest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"オオハクチョウ",
 nameI18n:{"ja":"オオハクチョウ","en":"Whooper Swan","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:13,
 star5:"虹 / 12〜18",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"コクチョウ",
 nameI18n:{"ja":"コクチョウ","en":"Black Swan","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:13,
 star5:"虹 / 12〜18",
 weather:["雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"郊外の湖",
 locationI18n:{"ja":"郊外の湖","en":"Suburban Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"クロクジャク",
 nameI18n:{"ja":"クロクジャク","en":"Black-shouldered Peafowl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:13,
 star5:"虹 / 12〜18",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"巣ごもりクエスト(追加段階)",
 locationI18n:{"ja":"巣ごもりクエスト(追加段階)","en":"Nesting Quest (Extra Stage)","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"ナベコウ",
 nameI18n:{"ja":"ナベコウ","en":"Black Stork","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:14,
 star5:"虹 / 12〜18",
 weather:["晴れ","雨","虹"],
 time:["12-18","18-0","0-6"],
 location:"草原の湖",
 locationI18n:{"ja":"草原の湖","en":"Grassland Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"メガネフクロウ",
 nameI18n:{"ja":"メガネフクロウ","en":"Spectacled Owl","zh-CN":"","zh-TW":"","ko":"","th":""},
 level:14,
 star5:"虹 / 6〜12",
 weather:["晴れ","雨","虹"],
 time:["6-12","0-6"],
 location:"森林-ジャンプステージ",
 locationI18n:{"ja":"森林-ジャンプステージ","en":"Forest - Jump Stage","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"images/000.PNG"
},
{
 name:"積み木スズメ(ピンク)",
 nameI18n:{"ja":"積み木スズメ(ピンク)","en":"Building Block Sparrow (Pink)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-石海岸の崖",
 locationI18n:{"ja":"温泉山-石海岸の崖","en":"Hot Spring Mountain - Rocky Coast Cliff","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/1001.PNG",
 auth:false
},
{
 name:"積み木スズメ(青)",
 nameI18n:{"ja":"積み木スズメ(青)","en":"Building Block Sparrow (Blue)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-温泉",
 locationI18n:{"ja":"温泉山-温泉","en":"Hot Spring Mountain - Hot Spring","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/1002.PNG",
 auth:false
},
{
 name:"積み木スズメ(緑)",
 nameI18n:{"ja":"積み木スズメ(緑)","en":"Building Block Sparrow (Green)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-火山湖",
 locationI18n:{"ja":"温泉山-火山湖","en":"Hot Spring Mountain - Volcanic Lake","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/1003.PNG",
 auth:false
},
{
 name:"積み木スズメ(紫)",
 nameI18n:{"ja":"積み木スズメ(紫)","en":"Building Block Sparrow (Purple)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:10,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"温泉山-遺跡",
 locationI18n:{"ja":"温泉山-遺跡","en":"Hot Spring Mountain - Ruins","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/1004.PNG",
 auth:false
},
{
 name:"積み木スズメ(虹)",
 nameI18n:{"ja":"積み木スズメ(虹)","en":"Building Block Sparrow (Rainbow)","zh-CN":"","zh-TW":"","ko":"","th":""},
 fes:true,
 ended:true,
 level:1,
 price:15,
 star5:"雨・虹 / 全時間",
 weather:["晴れ","雨","虹"],
 time:["6-12","12-18","18-0","0-6"],
 location:"特殊積み木鳥クエスト",
 locationI18n:{"ja":"特殊積み木鳥クエスト","en":"Special Building Block Bird Quest","zh-CN":"","zh-TW":"","ko":"","th":""},
 img:"birds/1005.PNG",
 auth:false
}
 // ここに追加していく
].map((c,i) => ({
  ...c,
  type:"bird",
  bookIndex:i
}));
